AAAAEngine: AAAAGameEngine2/AAAAGameEngine2/src/CoreEngine.cpp File Reference
CoreEngine.cpp File Reference
#include <iostream>
#include "Scripting.h"
#include "ECS.h"
#include "MeshLoader.h"
#include "Camera.h"
#include "terrain.h"
#include "GraphicsUtility.h"
#include "WorldPhysics.h"
#include "MeshRenderer.h"
#include "Renderer.h"
#include "Shader.h"
#include "LightingManager.h"
#include "Skybox.h"
#include "UI.h"
Functions
void processInput (GLFWwindow *window)
ENTITY AddEntity (Transform trans, bool render)
ENTITY CreateTerrain (std::string filepath, int size, int patchSize, float zfar, Transform trans, bool render)
void UseTerrain (bool use)
void AddMesh (ENTITY entity, WholeMesh &mesh)
void AddPhysicsBody (ENTITY entity)
void AddCamera (ENTITY entity, glm::vec3 pos, glm::vec3 lookAt, glm::vec3 up, double pitch, double yaw)
void DeleteEntity (ENTITY entity)
void DeleteMesh (ENTITY entity)
void DeletePhysicsBody (ENTITY entity)
void DeleteCamera (ENTITY entity)
WholeMesh & GetMesh (ENTITY entity)
PhysicsBody & GetPhysicsBody (ENTITY entity)
Camera & GetCamera (ENTITY entity)
Transform & GetTransform (ENTITY entity)
bool GetToRender (ENTITY entity)
Terrain & GetTerrain (ENTITY entity)
bool LoadMesh (std::string filepath)
WholeMesh RetrieveMesh ()
bool AddScript (std::string filepath)
void SetLuaObjects ()
void Start ()
void Update ()
int main (int argc, char *argv[])
Variables
const int WIDTH = 1920
const int HEIGHT = 1080
glm::vec3 cameraPosition = glm::vec3(0, 0, 0)
glm::vec3 cameraFront = glm::vec3(1.0f, 0.0f, 0.0f)
glm::vec3 cameraUp = glm::vec3(0.0f, 1.0f, 0.0f)
float cameraSpeed = 1.1f
float yaw = 0.0f
float pitch = 0.0f
bool renderingMode = true
ECS registry
MeshLoader loader
Scripting mainScript
bool useTerrain = false
Function Documentation
AddCamera()
void AddCamera (ENTITY entity, glm::vec3 pos, glm::vec3 lookAt, glm::vec3 up, double pitch, double yaw)
Definition at line 143 of file CoreEngine.cpp.
{
    registry.AddComponent<Camera>(entity, pos, lookAt, up, pitch, yaw);
}
AddEntity()
ENTITY AddEntity (Transform trans, bool render)
Definition at line 108 of file CoreEngine.cpp.
{
    ENTITY ent(registry.AddEntity(trans, render));
    return ent;
}
References ECS::AddEntity(), and registry.
Referenced by CreateTerrain(), and SetLuaObjects().
AddMesh()
void AddMesh (ENTITY entity, WholeMesh & mesh)
Definition at line 131 of file CoreEngine.cpp.
{
    registry.AddComponent<WholeMesh>(entity, mesh.materials, mesh.meshes);
}
References registry.
Referenced by SetLuaObjects().
AddPhysicsBody()
void AddPhysicsBody (ENTITY entity)
Definition at line 137 of file CoreEngine.cpp.
{
    registry.AddComponent<PhysicsBody>(entity);
}
References registry.
AddScript()
bool AddScript (std::string filepath)
Definition at line 223 of file CoreEngine.cpp.
{
    if (mainScript.LoadScript("scripts/" + filepath) < 0)
    {
        return false;
    }
    return true;
}
References Scripting::LoadScript(), and mainScript.
Referenced by SetLuaObjects().
CreateTerrain()
ENTITY CreateTerrain (std::string filepath, int size, int patchSize, float zfar, Transform trans, bool render)
Definition at line 116 of file CoreEngine.cpp.
{
    ENTITY entity(AddEntity(trans, render));
    registry.AddComponent<Terrain>(entity, filepath, size, patchSize, zfar);
    return entity;
}
References AddEntity(), and registry.
DeleteCamera()
void DeleteCamera (ENTITY entity)
Definition at line 167 of file CoreEngine.cpp.
{
    registry.DeleteComponent<Camera>(entity);
}
References registry.
DeleteEntity()
void DeleteEntity (ENTITY entity)
Definition at line 149 of file CoreEngine.cpp.
{
    registry.DeleteEntity(entity);
}
References ECS::DeleteEntity(), and registry.
DeleteMesh()
void DeleteMesh (ENTITY entity)
Definition at line 155 of file CoreEngine.cpp.
{
    registry.DeleteComponent<WholeMesh>(entity);
}
References registry.
DeletePhysicsBody()
void DeletePhysicsBody (ENTITY entity)
Definition at line 161 of file CoreEngine.cpp.
{
    registry.DeleteComponent<PhysicsBody>(entity);
}
References registry.
GetCamera()
Camera & GetCamera (ENTITY entity)
Definition at line 185 of file CoreEngine.cpp.
{
    return registry.GetComponent<Camera>(entity);
}
References registry.
GetMesh()
WholeMesh & GetMesh (ENTITY entity)
Definition at line 173 of file CoreEngine.cpp.
{
    return registry.GetComponent<WholeMesh>(entity);
}
References registry.
GetPhysicsBody()
PhysicsBody & GetPhysicsBody (ENTITY entity)
Definition at line 179 of file CoreEngine.cpp.
{
    return registry.GetComponent<PhysicsBody>(entity);
}
References registry.
GetTerrain()
Terrain & GetTerrain (ENTITY entity)
Definition at line 203 of file CoreEngine.cpp.
{
    return registry.GetComponent<Terrain>(entity);
}
References registry.
GetToRender()
bool GetToRender (ENTITY entity)
Definition at line 197 of file CoreEngine.cpp.
{
    return registry.GetComponent<ToRender>(entity).toRender;
}
References registry.
GetTransform()
Transform & GetTransform (ENTITY entity)
Definition at line 191 of file CoreEngine.cpp.
{
    return registry.GetComponent<Transform>(entity);
}
References registry.
LoadMesh()
bool LoadMesh (std::string filepath)
Definition at line 210 of file CoreEngine.cpp.
{
    return loader.LoadMesh(filepath);
}
References loader, and MeshLoader::LoadMesh().
Referenced by SetLuaObjects().
main()
int main (int argc, char * argv[])
Definition at line 353 of file CoreEngine.cpp.
{
    MeshRenderer meshRend;
    Renderer renderer;
    LightingManager lightingManager;
    /*glm::vec3 pos(cameraPosition);
    glm::vec3 rot(0, 0, 0);
    glm::vec3 scale(1, 1, 1);
    Transform trans(pos, rot, scale);
    ENTITY ent(AddEntity(trans, true));
    AddCamera(ent, cameraPosition, cameraFront, cameraUp, 0.0, 0.0);*/
    SetLuaObjects();
    GraphicsUtility::Initialise();
    GraphicsUtility::Window window = GraphicsUtility::CreateWindow("window");
    GraphicsUtility::makeContextCurrent(window);
    GraphicsUtility::initialiseOpenGLExtensions();
    GraphicsUtility::Enable(GraphicsEnum::DEPTH_TEST);
    Shader shaderT("resources/shaders/terrain.shader");
    Shader shaderL("resources/shaders/lighting.shader");
    Shader shaderS("resources/shaders/skybox.shader");
    Shader shader("resources/shaders/basic.shader");
    //Shader shaderMT("resources/shaders/multiTexture.shader");
    unsigned int dLight1 = lightingManager.CreateLight(glm::vec3(1, 1, 1), 0.3f, 1.0f, glm::vec3(-1, 0, 0));
    lightingManager.ActivateDirLight(dLight1);
    //unsigned int pLight1 = lightingManager.CreateLight({ 1.f, 0.f, 0.f }, 0.03f, 1.f, { 1, 1, 1 }, { 1.f, 0.2f, 0.f });
    //lightingManager.ActivatePointLight(pLight1);      gives generic linker error
    std::string filename = "scripts/TheMainScript.lua";
    if (mainScript.LoadScript(filename))
    {
        return -1;
    }
    InitPhysics();
    for (entt::entity entity : registry.Contains<Camera>())
    {
        std::cout << (unsigned int)entity << std::endl;
        if (GetToRender(entity))
        {
            std::cout << "found camera" << std::endl;
        }
    }
    //MeshLoader object;
    //object.LoadMesh("resources/models/4Story_Mat.obj");
    /*glm::vec3 pos1(0, 0, 0);
    glm::vec3 rot1(0, 0, 0);
    glm::vec3 scale1(1, 1, 1);
    Transform trans1(pos1, rot1, scale1);
    ENTITY obj(AddEntity(trans1, true));
    AddMesh(obj, object.GetMesh());*/
    Terrain terrain;
    if (useTerrain)
    {
        //terrain.genFaultFormation(32, 1025, -50, 1, 0.8, true, 33, 1000.0f);
        terrain.loadHeightMap("resources/heightmaps/VirusTerrain3.raw", 1025, 33, 500.0f);
        //terrain.loadTerrainTexture("resources/textures/grass.jpg");
        terrain.addProceduralTexture("resources/textures/newGrass.png");
        terrain.addProceduralTexture("resources/textures/newGrass.png");
        terrain.addProceduralTexture("resources/textures/rock.jpg");
        terrain.addProceduralTexture("resources/textures/snow.jpg");
        terrain.createProceduralTexture(glm::vec3(1.0f, 1.0f, 1.0f), glm::vec3(1.0f, 1.0f, 1.0f), glm::vec3(0.5f, 0.5f, 0.5f), 250.0f);
        terrain.loadDetailMapTexture("resources/textures/detail_map.jpg");
    }
    //terrain.loadTexture("resources/textures/money.jpg");
    //Skybox skybox(std::vector<std::string>({ "resources/textures/day1_right.png", "resources/textures/day1_left.png", "resources/textures/day1_top.png", "resources/textures/day1_bottom.png", "resources/textures/day1_front.png", "resources/textures/day1_back.png" }));
    Skybox skybox(std::vector<std::string>({ "resources/textures/mossymountains_right.png", "resources/textures/mossymountains_left.png", "resources/textures/mossymountains_up.png", "resources/textures/mossymountains_down.png", "resources/textures/mossymountains_front.png", "resources/textures/mossymountains_back.png" }));
    //Skybox skybox(std::vector<std::string>({ "resources/textures/mountain_right.png", "resources/textures/mountain_left.png", "resources/textures/mountain_top.png", "resources/textures/mountain_bottom.png", "resources/textures/mountain_front.png", "resources/textures/mountain_back.png" }));
    //registry.GetComponent<Camera>(ent).Set(glm::vec3(20, 10, 20), glm::vec3(2.0f, 1.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f), 0.0f, 0.0f);
    const char* items[] = { "Item 1", "Item 2", "Item 3" };
    int itemCount = sizeof(items) / sizeof(items[0]);
    int currentItem = 0; // Initial selected item index
    //Call start function
    mainScript.CallLUAFunction<void(*)()>("Start", &Start);
    bool cameraSet;
    while (!GraphicsUtility::shouldClose(window))
    {
        processInput(window);
        cameraSet = false;
        GraphicsUtility::SetClearColor(0.07f, 0.13f, 0.17f, 1.0f);
        GraphicsUtility::Clear(GraphicsEnum::COLOR_BUFFER_BIT | GraphicsEnum::DEPTH_BUFFER_BIT);
        UpdatePhysics();
        entt::entity camera;
        for (entt::entity entity : registry.Contains<Camera>())
        {
            if (registry.GetComponent<ToRender>(entity).toRender)
            {
                camera = entity;
                cameraSet = true;
            }
        }
        if (cameraSet)
        {
            meshRend.Render(registry, renderer, shaderL, registry.GetComponent<Camera>(camera).getViewMatrix(), registry.GetComponent<Camera>(camera).getProjectionMatrix(GraphicsUtility::GetWindowWidth(window), GraphicsUtility::GetWindowHeight(window), true, 90, 0.3f, 1000.f, 0.f));
        }
        else
        {
            std::cout << "Error: No camera object found in the scene" << std::endl;
        }
        //Call start function
        mainScript.CallLUAFunction<void(*)()>("Update", &Update);
        // Set up camera view matrix
        glm::mat4 view = glm::lookAt(cameraPosition, cameraPosition + cameraFront, cameraUp);
        // Set the projection matrix
        glm::mat4 projection = glm::perspective(glm::radians(45.0f), (float)1920 / (float)1080, 0.1f, 10000.0f); // Adjust far clipping plane to 10000.0f
        meshRend.Render(registry, renderer, shaderL, view, projection);
        //terrain.render(renderer, shaderT, registry.GetComponent<Camera>(camera).getViewMatrix(), registry.GetComponent<Camera>(camera).getProjectionMatrix(GraphicsUtility::GetWindowWidth(window), GraphicsUtility::GetWindowHeight(window), true, 90, 0.1f, 10000.f, 0.f));
        if(useTerrain)
        {
            terrain.render(renderer, shaderT, view, projection, cameraPosition);
        }
        //terrain.render(renderer, shaderT, camera1.getViewMatrix(), camera1.getProjectionMatrix(GraphicsUtility::GetWindowWidth(window), GraphicsUtility::GetWindowHeight(window), true, 90, 0.1f, 10000.f, 0.f));
        skybox.Render(renderer, shaderS, view, projection);
        // Swap front and back buffers
        GraphicsUtility::swapBuffers(window);
        // Poll for and process events
        GraphicsUtility::pollEvents();
    }
    GraphicsUtility::Terminate();
    return 0;
}
References LightingManager::ActivateDirLight(), Terrain::addProceduralTexture(), GraphicsUtility::Initialise(), GraphicsUtility::initialiseOpenGLExtensions(), InitPhysics(), Terrain::loadDetailMapTexture(), Terrain::loadHeightMap(), Scripting::LoadScript(), mainScript, SetLuaObjects(), Shader::Shader(), Start(), GraphicsUtility::Terminate(), and useTerrain.
processInput()
void processInput (GLFWwindow * window)
Definition at line 41 of file CoreEngine.cpp.
{
    // Forward/backward movement
    if (glfwGetKey(window, GLFW_KEY_W) == GLFW_PRESS)
        cameraPosition += cameraSpeed * cameraFront;
    if (glfwGetKey(window, GLFW_KEY_S) == GLFW_PRESS)
        cameraPosition -= cameraSpeed * cameraFront;
    // Strafe movement
    if (glfwGetKey(window, GLFW_KEY_A) == GLFW_PRESS)
        cameraPosition -= glm::normalize(glm::cross(cameraFront, cameraUp)) * cameraSpeed;
    if (glfwGetKey(window, GLFW_KEY_D) == GLFW_PRESS)
        cameraPosition += glm::normalize(glm::cross(cameraFront, cameraUp)) * cameraSpeed;
    // Camera rotation
    const float sensitivity = 0.1f;
    if (glfwGetKey(window, GLFW_KEY_LEFT) == GLFW_PRESS)
        yaw -= sensitivity;
    if (glfwGetKey(window, GLFW_KEY_RIGHT) == GLFW_PRESS)
        yaw += sensitivity;
    if (glfwGetKey(window, GLFW_KEY_UP) == GLFW_PRESS)
        pitch += sensitivity;
    if (glfwGetKey(window, GLFW_KEY_DOWN) == GLFW_PRESS)
        pitch -= sensitivity;
    // Clamp pitch to prevent camera flipping
    if (pitch > 89.0f)
        pitch = 89.0f;
    if (pitch < -89.0f)
        pitch = -89.0f;
    // Update camera front vector based on yaw and pitch
    glm::vec3 front;
    front.x = cos(glm::radians(yaw)) * cos(glm::radians(pitch));
    front.y = sin(glm::radians(pitch));
    front.z = sin(glm::radians(yaw)) * cos(glm::radians(pitch));
    cameraFront = glm::normalize(front);
    // Toggle between solid color and wireframe views when 'c' key is pressed
    static bool cKeyPressed = false;
    if (glfwGetKey(window, GLFW_KEY_C) == GLFW_PRESS) {
        if (!cKeyPressed) {
            if (renderingMode) {
                // Switch to wireframe
                glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                renderingMode = 0;
            }
            else {
                // Switch to solid color
                glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                renderingMode = 1;
            }
            cKeyPressed = true;
        }
    }
    else {
        cKeyPressed = false;
    }
}
References pitch, renderingMode, and yaw.
RetrieveMesh()
WholeMesh RetrieveMesh ()
Definition at line 216 of file CoreEngine.cpp.
{
    return loader.GetMesh();
}
References MeshLoader::GetMesh(), and loader.
Referenced by SetLuaObjects().
SetLuaObjects()
void SetLuaObjects ()
Definition at line 234 of file CoreEngine.cpp.
{
//Set Lua objects
//Data Structures
    //glm::vec3
    mainScript.RegisterCppObject<glm::vec3>(
        "Vector3",
        "x", &glm::vec3::x,
        "y", &glm::vec3::y,
        "z", &glm::vec3::z);
    //ENTITY
    mainScript.RegisterCppObject<ENTITY,
        char*, unsigned int(ENTITY::*)(),
        char*, void(ENTITY::*)(entt::entity)>("ENTITY",
            "Get", &ENTITY::Get,
            "Set", &ENTITY::Set);
    //bodytype
    mainScript.RegisterCppEnum<
        char*, bodytype,
        char*, bodytype,
        char*, bodytype>("BodyType",
            "STATIC", bodytype::STATIC,
            "KINEMATIC", bodytype::KINEMATIC,
            "DYNAMIC", bodytype::DYNAMIC);
//Components
    //Transform
    mainScript.RegisterCppObject<Transform,
        char*, glm::vec3& (Transform::*)(unsigned int),
        char*, void(Transform::*)(unsigned int, glm::vec3&)>("Transform",
            "Get", &Transform::Get,
            "Set", &Transform::Set);
    //PhysicsBody
    mainScript.RegisterCppObject<PhysicsBody,
        char*, Physics& (PhysicsBody::*)()>("PhysicsBody",
            "Get", &PhysicsBody::Get);
    //WholeMesh
    mainScript.RegisterCppObject<WholeMesh>("WholeMesh");
    //Camera
    mainScript.RegisterCppObject<Camera,
        char*, const glm::vec3(Camera::*)() const,
        char*, const glm::vec3(Camera::*)() const,
        char*, const glm::vec3(Camera::*)() const,
        char*, const double(Camera::*)() const,
        char*, const double(Camera::*)() const,
        char*, void(Camera::*)(glm::vec3, glm::vec3, glm::vec3, double, double)>("Camera",
            "position", &Camera::GetPosition,
            "lookAt", &Camera::GetForwardVector,
            "upVect", &Camera::GetUpVector,
            "pitch", &Camera::GetPitch,
            "yaw", &Camera::GetYaw,
            "Set", &Camera::Set);
    //PointLightSource
    //SpotLightSource
    //DirectionalLightSource
    //Terrain
//Classes
    //Scripting
    mainScript.SetCPPFunction<bool(*)(std::string)>("AddScript", &AddScript);
    //ECS
    mainScript.SetCPPFunction<ENTITY (*)(Transform, bool)>("CreateEntity", &AddEntity);
    //mainScript.SetCPPFunction<ENTITY (*)(std::string, int, Transform, bool)>("CreateTerrain", &AddTerrain);
    mainScript.SetCPPFunction<void (*)(ENTITY, glm::vec3, glm::vec3, glm::vec3, double, double)>("AddCamera", &AddCamera);
    mainScript.SetCPPFunction<void (*)(ENTITY, WholeMesh&)>("AddMesh", &AddMesh);
    mainScript.SetCPPFunction<void (*)(bool)>("UseTerrain", &UseTerrain);
    //Materials
    mainScript.RegisterCppObject<Material,
        char*, void(Material::*)(glm::vec3),
        char*, void(Material::*)(glm::vec3),
        char*, void(Material::*)(float),
        char*, void(Material::*)(glm::vec3),
        char*, const std::string(Material::*)() const,
        char*, void(Material::*)(std::string),
        char*, void(Material::*)(std::string) >("Material",
            "SetAmbientColour", &Material::SetAmbient,
            "SetSpecularColour", &Material::SetSpecular,
            "SetSpecularExponent", &Material::SetSpecularExponent,
            "SetDiffuseColour", &Material::SetDiffuse,
            "name", &Material::GetName,
            "SetName", &Material::SetName,
            "SetTexture", &Material::SetTextureFile);
    //MeshLoader
    mainScript.SetCPPFunction<bool(*)(std::string)>("LoadMesh", &LoadMesh);
    mainScript.SetCPPFunction<WholeMesh(*)()>("GetMesh", &RetrieveMesh);
    //Physics
    mainScript.RegisterCppObject<Physics,
        char*, void(Physics::*)(glm::vec3, float, bodytype, bool),
        char*, void(Physics::*)(glm::vec3, glm::vec3),
        char*, void(Physics::*)(glm::vec3, float),
        char*, void(Physics::*)(glm::vec3, float, float)>("Physics",
            "AddRigidbody", &Physics::addRigidBody,
            "AddBoxCollider", &Physics::addBox,
            "AddSphereCollider", &Physics::addSphere,
            "AddCapsuleCollider", &Physics::addCapsule);
}
References AddEntity(), AddMesh(), AddScript(), DYNAMIC, PhysicsBody::Get(), KINEMATIC, LoadMesh(), mainScript, RetrieveMesh(), STATIC, and UseTerrain().
Referenced by main().
Start()
void Start ()
Definition at line 349 of file CoreEngine.cpp.
{}
Referenced by main().
Update()
void Update ()
Definition at line 351 of file CoreEngine.cpp.
{}
UseTerrain()
void UseTerrain (bool use)
Definition at line 125 of file CoreEngine.cpp.
{
    useTerrain = use;
}
References useTerrain.
Referenced by SetLuaObjects().
Variable Documentation
cameraFront
glm::vec3 cameraFront = glm::vec3(1.0f, 0.0f, 0.0f)
Definition at line 27 of file CoreEngine.cpp.
cameraPosition
glm::vec3 cameraPosition = glm::vec3(0, 0, 0)
Definition at line 26 of file CoreEngine.cpp.
cameraSpeed
float cameraSpeed = 1.1f
Definition at line 32 of file CoreEngine.cpp.
cameraUp
glm::vec3 cameraUp = glm::vec3(0.0f, 1.0f, 0.0f)
Definition at line 28 of file CoreEngine.cpp.
HEIGHT
const int HEIGHT = 1080
Definition at line 23 of file CoreEngine.cpp.
loader
MeshLoader loader
Definition at line 101 of file CoreEngine.cpp.
Referenced by LoadMesh(), and RetrieveMesh().
mainScript
Scripting mainScript
Definition at line 102 of file CoreEngine.cpp.
Referenced by AddScript(), main(), and SetLuaObjects().
pitch
float pitch = 0.0f
Definition at line 36 of file CoreEngine.cpp.
Referenced by processInput().
registry
ECS registry
Definition at line 100 of file CoreEngine.cpp.
Referenced by AddEntity(), AddMesh(), AddPhysicsBody(), CreateTerrain(), DeleteCamera(), DeleteEntity(), DeleteMesh(), DeletePhysicsBody(), GetCamera(), GetMesh(), GetPhysicsBody(), GetTerrain(), GetToRender(), and GetTransform().
renderingMode
bool renderingMode = true
Definition at line 38 of file CoreEngine.cpp.
Referenced by processInput().
useTerrain
bool useTerrain = false
Definition at line 104 of file CoreEngine.cpp.
Referenced by main(), and UseTerrain().
WIDTH
const int WIDTH = 1920
Definition at line 22 of file CoreEngine.cpp.
yaw
float yaw = 0.0f
Definition at line 35 of file CoreEngine.cpp.
Referenced by processInput().