AAAAEngine: AAAAGameEngine2/AAAAGameEngine2/src/DataStructures.h File Reference
DataStructures.h File Reference
#include "glm.hpp"
#include "gtc/matrix_transform.hpp"
Classes
class Vector2
Class representing a 2D vector.
class Vector3
Class representing a 3D vector.
class Vector4
Class representing a 4D vector.
class Mat4x4
Class representing a 4x4 matrix.
class Mat3x3
Class representing a 3x3 matrix.
Functions
Mat4x4 LookAt (Vector3 position, Vector3 target, Vector3 up)
Mat4x4 Perspective (float fov, float aspect, float near, float far)
Mat4x4 Ortho (float left, float right, float bottom, float top, float near, float far)
Mat4x4 inverse (Mat4x4 mat)
Mat3x3 transpose (Mat3x3 mat)
Vector3 normalize (Vector3 vec)
Vector3 operator* (Vector3 &vec, Mat3x3 &mat)
Vector4 operator* (Vector4 &vec, Mat4x4 &mat)
Mat4x4 translate (Mat4x4 mat, Vector3 vec)
Mat4x4 rotate (Mat4x4 mat, float angle, Vector3 axis)
Mat4x4 scale (Mat4x4 mat, Vector3 vec)
float radians (float degrees)
Vector3 vec4To3 (Vector4 vec)
Function Documentation
inverse()
Mat4x4 inverse (Mat4x4 mat)
Calculates the inverse of a matrix.
Definition at line 209 of file DataStructures.cpp.
{
    return glm::inverse(static_cast<glm::mat4>(mat));
}
LookAt()
Mat4x4 LookAt (Vector3 position, Vector3 target, Vector3 up)
Constructs a view matrix.
Definition at line 189 of file DataStructures.cpp.
{
    return glm::lookAt(glm::vec3(position.x(), position.y(), position.z()),
        glm::vec3(target.x(), target.y(), target.z()),
        glm::vec3(up.x(), up.y(), up.z()));
}
normalize()
Vector3 normalize (Vector3 vec)
Normalizes a vector.
Definition at line 213 of file DataStructures.cpp.
{
    glm::vec3 normVec = glm::normalize(glm::vec3(vec.x(), vec.y(), vec.z()));
    return Vector3(normVec.x, normVec.y, normVec.z);
}
operator*() [1/2]
Vector3 operator* (Vector3 & vec, Mat3x3 & mat)
Multiplies a vector by a matrix.
Definition at line 219 of file DataStructures.cpp.
{
    float x = vec.x() * mat[0].x + vec.y() * mat[1].x + vec.z() * mat[2].x;
    float y = vec.x() * mat[0].y + vec.y() * mat[1].y + vec.z() * mat[2].y;
    float z = vec.x() * mat[0].z + vec.y() * mat[1].z + vec.z() * mat[2].z;
    return Vector3(x, y, z);
}
References Mat3x3::operator[](), Vector3::Vector3(), Vector3::x(), Vector3::y(), and Vector3::z().
operator*() [2/2]
Vector4 operator* (Vector4 & vec, Mat4x4 & mat)
Multiplies a vector by a matrix.
Definition at line 227 of file DataStructures.cpp.
{
    float x = vec.x() * mat[0].x() + vec.y() * mat[1].x() + vec.z() * mat[2].x() + vec.w() * mat[3].x();
    float y = vec.x() * mat[0].y() + vec.y() * mat[1].y() + vec.z() * mat[2].y() + vec.w() * mat[3].y();
    float z = vec.x() * mat[0].z() + vec.y() * mat[1].z() + vec.z() * mat[2].z() + vec.w() * mat[3].z();
    float w = vec.x() * mat[0].w() + vec.y() * mat[1].w() + vec.z() * mat[2].w() + vec.w() * mat[3].w();
    return Vector4(x, y, z, w);
}
References Mat4x4::operator[](), Vector4::Vector4(), Vector4::w(), Vector4::x(), Vector4::y(), and Vector4::z().
Ortho()
Mat4x4 Ortho (float left, float right, float bottom, float top, float near, float far)
Constructs an orthographic projection matrix.
Definition at line 200 of file DataStructures.cpp.
{
    return glm::ortho(left, right, bottom, top, near, far);
}
Perspective()
Mat4x4 Perspective (float fov, float aspect, float near, float far)
Constructs a perspective projection matrix.
Definition at line 196 of file DataStructures.cpp.
{
    return glm::perspective(fov, aspect, near, far);
}
radians()
float radians (float degrees)
Converts degrees to radians.
Definition at line 253 of file DataStructures.cpp.
{
        return glm::radians(degrees);
}
rotate()
Mat4x4 rotate (Mat4x4 mat, float angle, Vector3 axis)
Constructs a rotation matrix.
Definition at line 243 of file DataStructures.cpp.
{
        return glm::rotate(static_cast<glm::mat4>(mat), angle, glm::vec3(axis.x(), axis.y(), axis.z()));
}
scale()
Mat4x4 scale (Mat4x4 mat, Vector3 vec)
Constructs a scaling matrix.
Definition at line 248 of file DataStructures.cpp.
{
        return glm::scale(static_cast<glm::mat4>(mat), glm::vec3(vec.x(), vec.y(), vec.z()));
}
translate()
Mat4x4 translate (Mat4x4 mat, Vector3 vec)
Constructs a translation matrix.
Definition at line 238 of file DataStructures.cpp.
{
    return glm::translate(static_cast<glm::mat4>(mat), glm::vec3(vec.x(), vec.y(), vec.z()));
}
transpose()
Mat3x3 transpose (Mat3x3 mat)
Transposes a matrix.
Definition at line 204 of file DataStructures.cpp.
{
    return glm::transpose(static_cast<glm::mat3>(mat));
}
vec4To3()
Vector3 vec4To3 (Vector4 vec)
Converts a 4D vector to a 3D vector.
Definition at line 257 of file DataStructures.cpp.
{
    glm::vec4 newVec4(vec.x(), vec.y(), vec.z(), vec.w());
    glm::vec3 newVec3(newVec4);
    Vector3 result(newVec3.x, newVec3.y, newVec3.z);
    return result;
}