AAAAEngine: AAAAGameEngine2/AAAAGameEngine2/src/WorldPhysics.h File Reference
WorldPhysics.h File Reference
#include "reactphysics3d/reactphysics3d.h"
Functions
void InitPhysics ()
Initializes the physics world.
void setGravity (float x, float y, float z)
Sets the gravity for the physics world.
void setupPhysicsWorld (int VelocitySolverNbIterations, bool sleepEnabled, float gravityX, float gravityY, float gravityZ)
Sets up the physics world with specified parameters.
void UpdatePhysics ()
Updates the physics simulation.
Variables
static reactphysics3d::PhysicsWorld * world
static reactphysics3d::PhysicsCommon physicsCommon
static reactphysics3d::PhysicsWorld::WorldSettings settings
static float accumulator = 0.f
static const float timeStep = 1.f / 60.f
Function Documentation
InitPhysics()
void InitPhysics ()
Initializes the physics world.
Definition at line 3 of file WorldPhysics.cpp.
{
    setupPhysicsWorld(20, true, 0.0f, -9.81f, 0.0f);
}
References setupPhysicsWorld().
Referenced by main().
setGravity()
void setGravity (float x, float y, float z)
Sets the gravity for the physics world.
Parameters
x The x-component of the gravity vector.
y The y-component of the gravity vector.
z The z-component of the gravity vector.
Definition at line 8 of file WorldPhysics.cpp.
{
    reactphysics3d::Vector3 gravity(x, y, z);
    world->setGravity(gravity);
}
setupPhysicsWorld()
void setupPhysicsWorld (int VelocitySolverNbIterations, bool sleepEnabled, float gravityX, float gravityY, float gravityZ)
Sets up the physics world with specified parameters.
Parameters
VelocitySolverNbIterations The number of iterations for the velocity solver.
sleepEnabled Whether sleep is enabled for bodies.
gravityX The x-component of the gravity vector.
gravityY The y-component of the gravity vector.
gravityZ The z-component of the gravity vector.
Definition at line 14 of file WorldPhysics.cpp.
{
    settings.defaultVelocitySolverNbIterations = VelocitySolverNbIterations;
    settings.isSleepingEnabled = sleepEnabled;
    settings.gravity = reactphysics3d::Vector3(gravityX, gravityY, gravityZ);
}
Referenced by InitPhysics().
UpdatePhysics()
void UpdatePhysics ()
Updates the physics simulation.
Definition at line 22 of file WorldPhysics.cpp.
{
    while (accumulator >= timeStep)
    {
        world->update(timeStep);
        accumulator -= timeStep;
    }
}
References accumulator, and timeStep.
Variable Documentation
accumulator
float accumulator = 0.f static
The accumulator for physics simulation.
Definition at line 8 of file WorldPhysics.h.
Referenced by UpdatePhysics().
physicsCommon
reactphysics3d::PhysicsCommon physicsCommon static
The physics common object.
Definition at line 5 of file WorldPhysics.h.
settings
reactphysics3d::PhysicsWorld::WorldSettings settings static
Settings for the physics world.
Definition at line 6 of file WorldPhysics.h.
timeStep
const float timeStep = 1.f / 60.f static
The time step for physics simulation.
Definition at line 9 of file WorldPhysics.h.
Referenced by UpdatePhysics().
world
reactphysics3d::PhysicsWorld* world static
Pointer to the physics world.
Definition at line 4 of file WorldPhysics.h.