AAAAEngine: UI Class Reference
UI Class Reference
A class for creating user interface elements using ImGui.
#include <UI.h>
Public Member Functions
UI ()
Constructor.
~UI ()
Destructor.
void Initialise (GraphicsUtility::Window window)
Initializes the user interface.
void preRender ()
Prepares ImGui for rendering.
void postRender ()
Finishes rendering ImGui elements.
void cleanUp ()
Cleans up resources used by the UI.
void drawImage (const std::string &path, int x, int y, int width, int height, float scale)
Draws an image on the screen.
void drawWindow (const char *title, int x, int y, int width, int height, std::function< void()> windowContent)
Draws a window with custom content.
bool drawButton (const char *label, int x, int y, int width, int height, std::string fontType)
Draws a button with the specified label.
void drawText (const char *text, int x, int y, int size, std::string fontType)
Draws text on the screen.
void drawSlider (const char *label, int x, int y, int width, int height, float &value, float min, float max, std::string fontType)
Draws a slider control.
void drawCheckboxes (const std::vector< std::string > &labels, int x, int y, int width, int height, std::vector< bool > &values, std::string fontType)
Draws a group of checkboxes.
void drawRadioButtons (const std::vector< std::string > &labels, int x, int y, int width, int height, int &activeIndice, std::string fontType)
Draws a group of radio buttons.
void drawInputText (const char *label, int x, int y, int width, int height, char *buffer, int bufferSize, std::string fontType)
Draws an input text field.
void drawComboBox (const char *label, int x, int y, int width, int height, const char *items[], int itemCount, int &currentItem, std::string fontType)
Draws a combo box.
void drawProgressBar (float &progress, int x, int y, int width, int height, std::string fontType)
Draws a progress bar.
void drawListBox (const char *label, int x, int y, int width, int height, const char *items[], int itemCount, int &currentItem, std::string fontType)
Draws a list box.
void addFont (const char *name, const char *path, float size)
Adds a font to the UI.
void setStyleColor (ImGuiCol_ color, ImVec4 value)
Sets the color of a style element.
void setThemeDark ()
Sets the dark theme for the UI.
void setThemeLight ()
Sets the light theme for the UI.
void setWindowAlpha (float alpha)
Sets the transparency level of windows.
void setWindowRounding (float rounding)
Sets the rounding of window corners.
void setWindowBorderSize (float borderSize)
Sets the border size of windows.
void setFrameRounding (float rounding)
Sets the rounding of frame corners.
void setFrameBorderSize (float borderSize)
Sets the border size of frames.
Static Public Member Functions
static UI & GetInstance ()
Get the singleton instance of UI.
Private Attributes
std::map< std::string, ImFont * > fonts
Detailed Description
A class for creating user interface elements using ImGui.
Definition at line 17 of file UI.h.
Constructor & Destructor Documentation
UI()
UI::UI () default
Constructor.
~UI()
UI::~UI ()
Destructor.
Definition at line 6 of file UI.cpp.
        {
    cleanUp();
}
References cleanUp().
Member Function Documentation
addFont()
void UI::addFont (const char * name, const char * path, float size)
Adds a font to the UI.
Parameters
name The name of the font.
path The path to the font file.
size The size of the font.
Definition at line 41 of file UI.cpp.
{
    ImGuiIO& io = ImGui::GetIO();
    ImFont* font = io.Fonts->AddFontFromFileTTF(path, size);
    fonts[name] = font;
}
cleanUp()
void UI::cleanUp ()
Cleans up resources used by the UI.
Definition at line 10 of file UI.cpp.
                 {
    if (ImGui::GetCurrentContext() != nullptr) {
        ImGui_ImplOpenGL3_Shutdown();
        ImGui_ImplGlfw_Shutdown();
        ImGui::DestroyContext();
    }
}
Referenced by ~UI().
drawButton()
bool UI::drawButton (const char * label, int x, int y, int width, int height, std::string fontType)
Draws a button with the specified label.
Parameters
label The text label of the button.
x The x-coordinate of the top-left corner of the button.
y The y-coordinate of the top-left corner of the button.
width The width of the button.
height The height of the button.
fontType The name of the font to use for the button label.
Returns
True if the button is clicked, false otherwise.
Definition at line 127 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    ImGui::PushFont(fonts[fontType]);
    bool buttonPressed = ImGui::Button(label, ImVec2(width, height));
    ImGui::PopFont();
    return buttonPressed;
}
drawCheckboxes()
void UI::drawCheckboxes (const std::vector< std::string > & labels, int x, int y, int width, int height, std::vector< bool > & values, std::string fontType)
Draws a group of checkboxes.
Parameters
labels The labels for each checkbox.
x The x-coordinate of the top-left corner of the checkboxes group.
y The y-coordinate of the top-left corner of the checkboxes group.
width The width of the checkboxes group.
height The height of the checkboxes group.
values A vector containing the state of each checkbox.
fontType The name of the font to use for the labels.
Definition at line 143 of file UI.cpp.
{
    ImGui::PushFont(fonts[fontType]); // Assuming fonts is defined and initialized correctly
    for (size_t i = 0; i < labels.size(); ++i) {
        ImGui::SetCursorPos(ImVec2(x, y + i * height)); // Adjust y position for each checkbox
        bool value = values[i];
        if (ImGui::Checkbox(labels[i].c_str(), &value)) {
            values[i] = value;
        }
    }
    ImGui::PopFont();
}
drawComboBox()
void UI::drawComboBox (const char * label, int x, int y, int width, int height, const char * items[], int itemCount, int & currentItem, std::string fontType)
Draws a combo box.
Parameters
label The label of the combo box.
x The x-coordinate of the top-left corner of the combo box.
y The y-coordinate of the top-left corner of the combo box.
width The width of the combo box.
height The height of the combo box.
items An array of strings representing the items in the combo box.
itemCount The number of items in the combo box.
currentItem The index of the currently selected item.
fontType The name of the font to use for the label.
Definition at line 171 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    ImGui::PushFont(fonts[fontType]);
    ImGui::Combo(label, &currentItem, items, itemCount);
    ImGui::PopFont();
}
drawImage()
void UI::drawImage (const std::string & path, int x, int y, int width, int height, float scale)
Draws an image on the screen.
Parameters
path The path to the image file.
x The x-coordinate of the top-left corner of the image.
y The y-coordinate of the top-left corner of the image.
width The width of the image.
height The height of the image.
scale The scale factor of the image.
Definition at line 97 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    TextureManager::GetInstance().SetActiveTexture(path);
    unsigned int textureID = TextureManager::GetInstance().GetTexture(path);
    ImGui::Image((void*)textureID, ImVec2(width, height));
    TextureManager::GetInstance().Unbind();
}
References TextureManager::GetInstance(), TextureManager::GetTexture(), TextureManager::SetActiveTexture(), and TextureManager::Unbind().
drawInputText()
void UI::drawInputText (const char * label, int x, int y, int width, int height, char * buffer, int bufferSize, std::string fontType)
Draws an input text field.
Parameters
label The label of the input text field.
x The x-coordinate of the top-left corner of the input text field.
y The y-coordinate of the top-left corner of the input text field.
width The width of the input text field.
height The height of the input text field.
buffer The buffer to store the input text.
bufferSize The size of the buffer.
fontType The name of the font to use for the label.
Definition at line 164 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    ImGui::PushFont(fonts[fontType]);
    ImGui::InputText(label, buffer, bufferSize);
    ImGui::PopFont();
}
drawListBox()
void UI::drawListBox (const char * label, int x, int y, int width, int height, const char * items[], int itemCount, int & currentItem, std::string fontType)
Draws a list box.
Parameters
label The label of the list box.
x The x-coordinate of the top-left corner of the list box.
y The y-coordinate of the top-left corner of the list box.
width The width of the list box.
height The height of the list box.
items An array of strings representing the items in the list box.
itemCount The number of items in the list box.
currentItem The index of the currently selected item.
fontType The name of the font to use for the label.
Definition at line 185 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    ImGui::PushFont(fonts[fontType]);
    ImGui::ListBox(label, &currentItem, items, itemCount);
    ImGui::PopFont();
}
drawProgressBar()
void UI::drawProgressBar (float & progress, int x, int y, int width, int height, std::string fontType)
Draws a progress bar.
Parameters
progress A reference to the progress value.
x The x-coordinate of the top-left corner of the progress bar.
y The y-coordinate of the top-left corner of the progress bar.
width The width of the progress bar.
height The height of the progress bar.
fontType The name of the font to use for the label.
Definition at line 178 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    ImGui::PushFont(fonts[fontType]);
    ImGui::ProgressBar(progress, ImVec2(width, height));
    ImGui::PopFont();
}
drawRadioButtons()
void UI::drawRadioButtons (const std::vector< std::string > & labels, int x, int y, int width, int height, int & activeIndice, std::string fontType)
Draws a group of radio buttons.
Parameters
labels The labels for each radio button.
x The x-coordinate of the top-left corner of the radio buttons group.
y The y-coordinate of the top-left corner of the radio buttons group.
width The width of the radio buttons group.
height The height of the radio buttons group.
activeIndice The index of the active radio button.
fontType The name of the font to use for the labels.
Definition at line 155 of file UI.cpp.
{
    ImGui::PushFont(fonts[fontType]);
    for (size_t i = 0; i < labels.size(); ++i) {
        ImGui::SetCursorPos(ImVec2(x, y + i * height)); // Adjust y position for each radio button
        ImGui::RadioButton(labels[i].c_str(), &activeIndex, i);
    }
    ImGui::PopFont();
}
drawSlider()
void UI::drawSlider (const char * label, int x, int y, int width, int height, float & value, float min, float max, std::string fontType)
Draws a slider control.
Parameters
label The label of the slider.
x The x-coordinate of the top-left corner of the slider.
y The y-coordinate of the top-left corner of the slider.
width The width of the slider.
height The height of the slider.
value A reference to the value controlled by the slider.
min The minimum value of the slider.
max The maximum value of the slider.
fontType The name of the font to use for the label.
Definition at line 136 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    ImGui::PushFont(fonts[fontType]);
    ImGui::SliderFloat(label, &value, min, max);
    ImGui::PopFont();
}
drawText()
void UI::drawText (const char * text, int x, int y, int size, std::string fontType)
Draws text on the screen.
Parameters
text The text to draw.
x The x-coordinate of the top-left corner of the text.
y The y-coordinate of the top-left corner of the text.
size The size of the text.
fontType The name of the font to use for the text.
Definition at line 192 of file UI.cpp.
{
    ImGui::SetCursorPos(ImVec2(x, y));
    ImGui::PushFont(fonts[fontType]);
    ImGui::Text(text);
    ImGui::PopFont();
}
drawWindow()
void UI::drawWindow (const char * title, int x, int y, int width, int height, std::function< void()> windowContent)
Draws a window with custom content.
Parameters
title The title of the window.
x The x-coordinate of the top-left corner of the window.
y The y-coordinate of the top-left corner of the window.
width The width of the window.
height The height of the window.
windowContent The function that renders the window content.
Definition at line 105 of file UI.cpp.
{
    ImGui::SetNextWindowPos(ImVec2(x, y));
    ImGui::SetNextWindowSize(ImVec2(width, height));
    // Push font if available
    if (fonts.count("Title") > 0) {
        ImGui::PushFont(fonts["Title"]);
    }
    ImGui::Begin(title, NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoMove);
    // Call the provided function to render the window content
    windowContent();
    ImGui::End(); // Close the window
    // Pop font if one was pushed
    if (fonts.count("Title") > 0) {
        ImGui::PopFont();
    }
}
GetInstance()
UI & UI::GetInstance () static
Get the singleton instance of UI.
Returns
Reference to the UI instance.
Definition at line 18 of file UI.cpp.
                    {
    static UI instance;
    return instance;
}
Initialise()
void UI::Initialise (GraphicsUtility::Window window)
Initializes the user interface.
Parameters
window The GLFW window.
Definition at line 23 of file UI.cpp.
{
    //try catch for imgui initialisation
    try {
        IMGUI_CHECKVERSION();
        ImGui::CreateContext();
        ImGui_ImplGlfw_InitForOpenGL(window, true);
        ImGui_ImplOpenGL3_Init("#version 410");
    }
    catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
    }
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    io.Fonts->AddFontDefault();
}
postRender()
void UI::postRender ()
Finishes rendering ImGui elements.
Definition at line 92 of file UI.cpp.
                    {
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
}
preRender()
void UI::preRender ()
Prepares ImGui for rendering.
Definition at line 86 of file UI.cpp.
                   {
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
}
setFrameBorderSize()
void UI::setFrameBorderSize (float borderSize)
Sets the border size of frames.
Parameters
borderSize The border size value.
Definition at line 81 of file UI.cpp.
{
    ImGuiStyle& style = ImGui::GetStyle();
    style.FrameBorderSize = borderSize;
}
setFrameRounding()
void UI::setFrameRounding (float rounding)
Sets the rounding of frame corners.
Parameters
rounding The rounding value.
Definition at line 76 of file UI.cpp.
{
    ImGuiStyle& style = ImGui::GetStyle();
    style.FrameRounding = rounding;
}
setStyleColor()
void UI::setStyleColor (ImGuiCol_ color, ImVec4 value)
Sets the color of a style element.
Parameters
color The ImGuiCol_ enum representing the style element.
value The new color value.
Definition at line 47 of file UI.cpp.
{
    ImGui::StyleColorsDark();
    ImGuiStyle& style = ImGui::GetStyle();
    style.Colors[color] = value;
}
setThemeDark()
void UI::setThemeDark ()
Sets the dark theme for the UI.
Definition at line 53 of file UI.cpp.
                      {
    ImGui::StyleColorsDark();
}
setThemeLight()
void UI::setThemeLight ()
Sets the light theme for the UI.
Definition at line 57 of file UI.cpp.
                       {
    ImGui::StyleColorsLight();
}
setWindowAlpha()
void UI::setWindowAlpha (float alpha)
Sets the transparency level of windows.
Parameters
alpha The alpha value (0.0 = fully transparent, 1.0 = fully opaque).
Definition at line 61 of file UI.cpp.
{
    ImGuiStyle& style = ImGui::GetStyle();
    style.WindowRounding = alpha;
}
setWindowBorderSize()
void UI::setWindowBorderSize (float borderSize)
Sets the border size of windows.
Parameters
borderSize The border size value.
Definition at line 71 of file UI.cpp.
{
    ImGuiStyle& style = ImGui::GetStyle();
    style.WindowBorderSize = borderSize;
}
setWindowRounding()
void UI::setWindowRounding (float rounding)
Sets the rounding of window corners.
Parameters
rounding The rounding value.
Definition at line 66 of file UI.cpp.
{
    ImGuiStyle& style = ImGui::GetStyle();
    style.WindowRounding = rounding;
}
Member Data Documentation
fonts
std::map<std::string, ImFont*> UI::fonts private
Definition at line 248 of file UI.h.
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/UI.h
AAAAGameEngine2/AAAAGameEngine2/src/UI.cpp