AAAAEngine: Vector3 Class Reference
Vector3 Class Reference
Class representing a 3D vector.
#include <DataStructures.h>
Public Member Functions
Vector3 ()
Vector3 (float x, float y, float z)
float & x ()
float & y ()
float & z ()
void SetX (float n)
void SetY (float n)
void SetZ (float n)
int length ()
void normalise ()
void Set (float x, float y, float z)
operator glm::vec3 () const
const Vector3 operator+ (const Vector3 &other) const
Private Attributes
glm::vec3 data
Detailed Description
Class representing a 3D vector.
Definition at line 37 of file DataStructures.h.
Constructor & Destructor Documentation
Vector3() [1/2]
Vector3::Vector3 () inline
Definition at line 43 of file DataStructures.h.
: data(glm::vec3(0.0f)) {}
Vector3() [2/2]
Vector3::Vector3 (float x, float y, float z) inline
Definition at line 44 of file DataStructures.h.
: data(glm::vec3(x, y, z)) {}
Referenced by operator*().
Member Function Documentation
length()
int Vector3::length ()
Definition at line 53 of file DataStructures.cpp.
{
    return data.length();
}
normalise()
void Vector3::normalise ()
Definition at line 58 of file DataStructures.cpp.
{
    data = glm::normalize(data);
}
operator glm::vec3()
Vector3::operator glm::vec3 () const
Conversion operator to glm::vec3.
Definition at line 70 of file DataStructures.cpp.
{
    return data;
}
operator+()
const Vector3 Vector3::operator+ (const Vector3 & other) const
Addition operator for vectors.
Definition at line 75 of file DataStructures.cpp.
{
    return Vector3(this->data.x + other.data.x, this->data.y + other.data.y, this->data.z + other.data.z);
}
Set()
void Vector3::Set (float x, float y, float z)
Definition at line 63 of file DataStructures.cpp.
{
    data.x = x;
    data.y = y;
    data.z = z;
}
SetX()
void Vector3::SetX (float n) inline
Sets the value of the x component.
Definition at line 50 of file DataStructures.h.
SetY()
void Vector3::SetY (float n) inline
Sets the value of the y component.
Definition at line 51 of file DataStructures.h.
SetZ()
void Vector3::SetZ (float n) inline
Sets the value of the z component.
Definition at line 52 of file DataStructures.h.
x()
float & Vector3::x ()
Returns a reference to the x component of the vector.
Definition at line 38 of file DataStructures.cpp.
{
    return data.x;
}
Referenced by operator*().
y()
float & Vector3::y ()
Returns a reference to the y component of the vector.
Definition at line 43 of file DataStructures.cpp.
{
    return data.y;
}
Referenced by operator*().
z()
float & Vector3::z ()
Returns a reference to the z component of the vector.
Definition at line 48 of file DataStructures.cpp.
{
    return data.z;
}
Referenced by operator*().
Member Data Documentation
data
glm::vec3 Vector3::data private
Internal data storage for the vector.
Definition at line 40 of file DataStructures.h.
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/DataStructures.h
AAAAGameEngine2/AAAAGameEngine2/src/DataStructures.cpp