AAAAEngine: LightingManager Class Reference
LightingManager Class Reference
A class responsible for managing various types of lights in a 3D scene.
#include <LightingManager.h>
Public Member Functions
LightingManager ()
Default constructor for LightingManager.
~LightingManager ()
Destructor for LightingManager.
unsigned int CreateLight (glm::vec3 colour, float aIntensity, float dIntensity, glm::vec3 direction)
Create a directional light.
unsigned int CreateLight (glm::vec3 colour, float aIntensity, float dIntensity, glm::vec3 position, glm::vec3 atten)
Create a point light.
unsigned int CreateLight (glm::vec3 colour, float aIntensity, float dIntensity, glm::vec3 position, float angle, float range)
Create a spot light.
void ActivateDirLight (unsigned int currLight)
Activate a directional light with the given ID.
void ActivatePointLight (unsigned int currLight)
Activate a point light with the given ID.
void DeactivateDirLight ()
Deactivate the directional light.
void DeactivatePointLight (unsigned int delLight)
Deactivate a point light with the given ID.
int GetActiveDirLight ()
Get the ID of the active directional light.
std::vector< unsigned int > GetActivePointLights ()
Get a list of active point lights.
Static Public Member Functions
static int GetIsDirLight ()
Get the status of directional light.
static void SetLightingUniforms (Shader &shader, glm::mat4 modelmatrix)
Set lighting uniforms in a shader program.
Private Member Functions
void UpdateActivePoints ()
Set point light uniforms in a shader program.
Static Private Member Functions
static void SetDirectionalUniforms (Shader &shader)
Set directional light uniforms in a shader program.
static void SetPointUniforms (Shader &shader, glm::mat4 worldMatrix)
Set point light uniforms in a shader program.
Static Private Attributes
static std::vector< DirectionalLightSource > m_dirLights
static std::vector< PointLightSource > m_pointLights
static std::vector< SpotLightSource > m_spotLights
static const unsigned int m_maxLights = 1
static int m_activeDirLight
static std::vector< unsigned int > m_activePointLights
static std::vector< glm::vec4 > m_pointLightColours
static std::vector< float > m_ambientIntensies
static std::vector< float > m_diffuseIntensies
static std::vector< float > m_constants
static std::vector< float > m_linears
static std::vector< float > m_exps
static int m_isDirLight
Detailed Description
A class responsible for managing various types of lights in a 3D scene.
Definition at line 22 of file LightingManager.h.
Constructor & Destructor Documentation
LightingManager()
LightingManager::LightingManager ()
Default constructor for LightingManager.
Definition at line 21 of file LightingManager.cpp.
{
    m_ambientIntensies = std::vector<float>();
    m_diffuseIntensies = std::vector<float>();
    m_constants = std::vector<float>();
    m_linears = std::vector<float>();
    m_exps = std::vector<float>();
}
~LightingManager()
LightingManager::~LightingManager ()
Destructor for LightingManager.
Definition at line 30 of file LightingManager.cpp.
{
}
Member Function Documentation
ActivateDirLight()
void LightingManager::ActivateDirLight (unsigned int currLight)
Activate a directional light with the given ID.
Parameters
currLight The ID of the directional light to activate.
Definition at line 77 of file LightingManager.cpp.
{
    m_activeDirLight = currLight;
    UpdateActivePoints();
    if (m_isDirLight == 0)
    {
        m_isDirLight = 1;
        //std::cout << "Activate: " << m_isDirLight << std::endl;
    }
}
References m_activeDirLight, m_isDirLight, and UpdateActivePoints().
Referenced by main().
ActivatePointLight()
void LightingManager::ActivatePointLight (unsigned int currLight)
Activate a point light with the given ID.
Parameters
currLight The ID of the point light to activate.
Definition at line 91 of file LightingManager.cpp.
{
    m_activePointLights.push_back(currLight);
    UpdateActivePoints();
}
References UpdateActivePoints().
CreateLight() [1/3]
unsigned int LightingManager::CreateLight (glm::vec3 colour, float aIntensity, float dIntensity, glm::vec3 direction)
Create a directional light.
Parameters
colour The light color.
aIntensity The ambient intensity of the light.
dIntensity The diffuse intensity of the light.
direction The direction of the light.
Returns
An ID for the created light.
Definition at line 35 of file LightingManager.cpp.
{
    DirectionalLightSource newLight(colour, aIntensity, dIntensity, direction);
    m_ambientIntensies.push_back(aIntensity);
    m_diffuseIntensies.push_back(dIntensity);
    m_constants.push_back(0.f);
    m_linears.push_back(0.f);
    m_exps.push_back(0.f);
    m_dirLights.push_back(newLight);
    return m_dirLights.size() - 1;
}
CreateLight() [2/3]
unsigned int LightingManager::CreateLight (glm::vec3 colour, float aIntensity, float dIntensity, glm::vec3 position, float angle, float range)
Create a spot light.
Parameters
colour The light color.
aIntensity The ambient intensity of the light.
dIntensity The diffuse intensity of the light.
position The position of the light.
angle The light angle.
range The light range.
Returns
An ID for the created light.
Definition at line 64 of file LightingManager.cpp.
{
    SpotLightSource newLight(colour, aIntensity, dIntensity, position, angle, range);
    m_ambientIntensies.push_back(aIntensity);
    m_diffuseIntensies.push_back(dIntensity);
    m_spotLights.push_back(newLight);
    m_constants.push_back(0.f);
    m_linears.push_back(0.f);
    m_exps.push_back(0.f);
    return m_spotLights.size() - 1;
}
CreateLight() [3/3]
unsigned int LightingManager::CreateLight (glm::vec3 colour, float aIntensity, float dIntensity, glm::vec3 position, glm::vec3 atten)
Create a point light.
Parameters
colour The light color.
aIntensity The ambient intensity of the light.
dIntensity The diffuse intensity of the light.
position The position of the light.
atten The attenuation parameters.
Returns
An ID for the created light.
Definition at line 50 of file LightingManager.cpp.
{
    PointLightSource newLight(colour, aIntensity, dIntensity, position, atten);
    m_ambientIntensies.push_back(aIntensity);
    m_diffuseIntensies.push_back(dIntensity);
    m_constants.push_back(atten.x);
    m_linears.push_back(atten.y);
    m_exps.push_back(atten.z);
    m_pointLights.push_back(newLight);
    return m_pointLights.size() - 1;
}
DeactivateDirLight()
void LightingManager::DeactivateDirLight ()
Deactivate the directional light.
Definition at line 98 of file LightingManager.cpp.
{
    m_activeDirLight = -1;
    if (m_isDirLight == 1)
    {
        m_isDirLight = 0;
        //std::cout << "Deactivate: " << m_isDirLight << std::endl;
    }
}
References m_activeDirLight, and m_isDirLight.
DeactivatePointLight()
void LightingManager::DeactivatePointLight (unsigned int delLight)
Deactivate a point light with the given ID.
Parameters
delLight The ID of the point light to deactivate.
Definition at line 110 of file LightingManager.cpp.
{
    m_activePointLights.erase(std::remove(m_activePointLights.begin(), m_activePointLights.end(), delLight), m_activePointLights.end());
    UpdateActivePoints();
}
References UpdateActivePoints().
GetActiveDirLight()
int LightingManager::GetActiveDirLight ()
Get the ID of the active directional light.
Returns
The ID of the active directional light.
Definition at line 176 of file LightingManager.cpp.
{
    if (m_isDirLight == 1)
    {
        return m_activeDirLight;
    }
    else
    {
        return -1;
    }
}
References m_activeDirLight, and m_isDirLight.
GetActivePointLights()
std::vector< unsigned int > LightingManager::GetActivePointLights ()
Get a list of active point lights.
Returns
A vector of IDs of active point lights.
Definition at line 188 of file LightingManager.cpp.
{
    return m_activePointLights;
}
GetIsDirLight()
int LightingManager::GetIsDirLight () static
Get the status of directional light.
Returns
1 if a directional light is active, 0 otherwise.
Definition at line 117 of file LightingManager.cpp.
{
    return m_isDirLight;
}
References m_isDirLight.
Referenced by Terrain::render().
SetDirectionalUniforms()
void LightingManager::SetDirectionalUniforms (Shader & shader) static private
Set directional light uniforms in a shader program.
Parameters
shader The shader program to set the directional light uniforms in.
Definition at line 129 of file LightingManager.cpp.
{
    unsigned int active;
    if (m_activeDirLight == -1)
    {
        active = 0;
    }
    else
    {
        active = m_activeDirLight;
    }
    //Ambient Lighting
    shader.SetUniform1f("u_AmbientIntensity", m_dirLights[active].GetIntensity());
    shader.SetUniform4f("u_LightColour", glm::vec4(m_dirLights[active].GetColour(), 1.0f ));
    //Diffuse Lighting
    glm::vec3 LDirection = m_dirLights[active].GetLDirection();
    shader.SetUniform3f("u_Direction", LDirection);
    shader.SetUniform1f("u_DiffuseIntensity", m_dirLights[active].GetDIntensity());
}
References m_activeDirLight.
Referenced by SetLightingUniforms().
SetLightingUniforms()
void LightingManager::SetLightingUniforms (Shader & shader, glm::mat4 modelmatrix) static
Set lighting uniforms in a shader program.
Parameters
shader The shader program to set the lighting uniforms in.
modelmatrix The model matrix for the object being rendered.
Definition at line 122 of file LightingManager.cpp.
{
    SetDirectionalUniforms(shader);
    SetPointUniforms(shader, modelMatrix);
}
References SetDirectionalUniforms().
SetPointUniforms()
void LightingManager::SetPointUniforms (Shader & shader, glm::mat4 worldMatrix) static private
Set point light uniforms in a shader program.
Parameters
shader The shader program to set the point light uniforms in.
worldMatrix The world matrix of the object being rendered.
Definition at line 152 of file LightingManager.cpp.
{
    m_pointLightColours.clear();
    std::vector<glm::vec3> positions;
    for (int i = 0; i < m_maxLights; i++)
    {
        if (i < m_activePointLights.size())
        {
            positions.push_back(m_pointLights[i].GetLocalPosition(worldMatrix));
            m_pointLightColours.push_back({ m_pointLights[m_activePointLights[i]].GetColour(), 1.0f });
        }
    }
    shader.SetUniform3fv("u_PointPositions", m_maxLights, positions);
    shader.SetUniform4fv("u_PointColours", m_maxLights, m_pointLightColours);
    shader.SetUniform1fv("u_PointAmbientIntensities", m_maxLights, m_ambientIntensies.data());
    shader.SetUniform1fv("u_PointDiffuseIntensities", m_maxLights, m_diffuseIntensies.data());
    shader.SetUniform1fv("u_PointConstants", m_maxLights, m_constants.data());
    shader.SetUniform1fv("u_PointLinears", m_maxLights, m_linears.data());
    shader.SetUniform1fv("u_PointExps", m_maxLights, m_exps.data());
    shader.SetUniform1i("u_NumOfPoints", m_activePointLights.size());
}
References m_maxLights.
UpdateActivePoints()
void LightingManager::UpdateActivePoints () private
Set point light uniforms in a shader program.
Parameters
shader The shader program to set the point light uniforms in.
worldMatrix The world matrix of the object being rendered.
Definition at line 193 of file LightingManager.cpp.
{
    for (int i = 0; i < m_maxLights; i++)
    {
        m_constants[i] = 0.f;
        m_linears[i] = 0.f;
        m_exps[i] = 0.f;
        m_ambientIntensies[i] = 0.f;
        m_diffuseIntensies[i] = 0.f;
    }
    for (int i = 0; i < m_maxLights; i++)
    {
        //std::cout << m_activePointLights.size() << std::endl;
        if (i < m_activePointLights.size())
        {
            glm::vec3 atten = m_pointLights[m_activePointLights[i]].GetAttenuation();
            m_constants[i] = atten.x;
            m_linears[i] = atten.y;
            m_exps[i] = atten.z;
            m_ambientIntensies[i] = m_pointLights[m_activePointLights[i]].GetIntensity();
            m_diffuseIntensies[i] = m_pointLights[m_activePointLights[i]].GetDIntensity();
            //std::cout << "\nconst: " << m_constants[i] << "\nlin: " << m_linears[i] << "\nexp: " << m_exps[i] << "\namb: " <<
                //m_ambientIntensies[i] << "\ndiff: " << m_diffuseIntensies[i] << std::endl;
        }
    }
}
References m_maxLights.
Referenced by ActivateDirLight(), ActivatePointLight(), and DeactivatePointLight().
Member Data Documentation
m_activeDirLight
int LightingManager::m_activeDirLight static private
Definition at line 134 of file LightingManager.h.
Referenced by ActivateDirLight(), DeactivateDirLight(), GetActiveDirLight(), and SetDirectionalUniforms().
m_activePointLights
std::vector< unsigned int > LightingManager::m_activePointLights static private
Definition at line 135 of file LightingManager.h.
m_ambientIntensies
std::vector< float > LightingManager::m_ambientIntensies static private
Definition at line 137 of file LightingManager.h.
m_constants
std::vector< float > LightingManager::m_constants static private
Definition at line 139 of file LightingManager.h.
m_diffuseIntensies
std::vector< float > LightingManager::m_diffuseIntensies static private
Definition at line 138 of file LightingManager.h.
m_dirLights
std::vector< DirectionalLightSource > LightingManager::m_dirLights static private
Definition at line 130 of file LightingManager.h.
m_exps
std::vector< float > LightingManager::m_exps static private
Definition at line 141 of file LightingManager.h.
m_isDirLight
int LightingManager::m_isDirLight static private
Definition at line 142 of file LightingManager.h.
Referenced by ActivateDirLight(), DeactivateDirLight(), GetActiveDirLight(), and GetIsDirLight().
m_linears
std::vector< float > LightingManager::m_linears static private
Definition at line 140 of file LightingManager.h.
m_maxLights
const unsigned int LightingManager::m_maxLights = 1 static private
Definition at line 133 of file LightingManager.h.
Referenced by SetPointUniforms(), and UpdateActivePoints().
m_pointLightColours
std::vector< glm::vec4 > LightingManager::m_pointLightColours static private
Definition at line 136 of file LightingManager.h.
m_pointLights
std::vector< PointLightSource > LightingManager::m_pointLights static private
Definition at line 131 of file LightingManager.h.
m_spotLights
std::vector< SpotLightSource > LightingManager::m_spotLights static private
Definition at line 132 of file LightingManager.h.
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/LightingManager.h
AAAAGameEngine2/AAAAGameEngine2/src/LightingManager.cpp