AAAAEngine: Terrain Class Reference
Terrain Class Reference
Represents a terrain object.
#include <terrain.h>
Classes
struct LODInfo
struct SingleLODInfo
Public Member Functions
Terrain (float scaleX=1.f, float scaleY=1.f, float scaleZ=1.f)
Constructs a Terrain object with default scale values.
Terrain (std::string filename, int size, int patchSize, float zfar)
Constructs a Terrain object from a heightmap file.
~Terrain ()
Default destructor for Terrain.
bool loadHeightMap (const std::string &fileName, const int size, int patchSize, float zfar)
Loads a heightmap from a file.
void loadTerrainTexture (const std::string &fileName, glm::vec3 ambient, glm::vec3 diffuse, glm::vec3 specular, float specEx)
Loads a texture for the terrain.
void loadDetailMapTexture (const std::string &fileName)
Loads a detail map texture for the terrain.
float getHeight (int xpos, int zpos)
Gets the height at a specific position on the terrain.
const int getSize () const
Gets the size of the terrain.
void render (const Renderer &renderer, Shader &shader, const glm::mat4 &viewMatrix, const glm::mat4 &projectionMatrix, glm::vec3 CameraPosition)
Renders the terrain.
bool createProceduralTexture (glm::vec3 ambient, glm::vec3 diffuse, glm::vec3 specular, float specEx)
Creates a procedural texture for the terrain.
bool genFaultFormation (int iterations, int hSize, int minHeight, int maxHeight, float weight, bool random, int patchSize, float zfar)
Generates a terrain using the fault formation algorithm.
void setHeightAtPoint (float height, int xpos, int zpos)
Sets the height at a specific position on the terrain.
bool addProceduralTexture (const std::string &fileName)
Adds a procedural texture to the terrain.
Private Member Functions
unsigned int AddTriangle (unsigned int Index, std::vector< unsigned int > &Indices, unsigned int v1, unsigned int v2, unsigned int v3)
Adds a triangle to the index buffer.
int InitIndices (std::vector< unsigned int > &Indices)
Initializes the index buffer.
int InitIndicesLOD (int Index, std::vector< unsigned int > &indices, int LOD)
Initializes the index buffer for a given level of detail.
int InitIndicesLODSingle (int Index, std::vector< unsigned int > &indices, int LODCore, int LODLeft, int LODRight, int LODTop, int LODBottom)
Initializes the index buffer for a given level of detail (single patch).
unsigned int createTriangeFan (int Index, std::vector< unsigned int > &indices, int LODCore, int LODLeft, int LODRight, int LODTop, int LODBottom, int x, int z)
Creates a triangle fan for a given patch.
int calcNumIndices ()
Calculates the number of indices.
void generateTerrainBuffers ()
Generates the vertex and index buffers for the terrain.
void CalcLODNormals (std::vector< float > &Vertices, std::vector< unsigned int > &Indices)
Calculates normals for the terrain based on vertices and indices.
void CreateGeomipmapGrid (int width, int depth, int patchSize, float zfar)
Creates a geomipmap grid for the terrain.
void filterPass (float *startP, int increment, float weight)
Applies a filter pass to the terrain data.
void addFilter (std::vector< float > &terrainData, float weight)
Adds a filter to the terrain data.
void normaliseTerrain (std::vector< float > &terrainData)
Normalizes the terrain data.
glm::vec3 CalcNormal (int x, int z)
Calculates the normal at a specific position on the terrain.
bool inbounds (int xpos, int zpos)
Checks if a position is within the bounds of the terrain.
void getTexCoord (int texNum, unsigned int &x, unsigned int &y)
Calculates the texture coordinates for a given texture number.
Private Attributes
int m_Size
unsigned int m_Width
unsigned int m_Length
std::vector< float > m_Heights
float scaleX
float scaleY
float scaleZ
TextureGenerator texGen
std::string terrainTextureFile
std::string detailMapTextureFile
VertexArray m_VAO
std::unique_ptr< VertexBuffer > m_VBO
std::unique_ptr< IndexBuffer > m_IBO
Material material
int m_patchSize
int m_maxLOD
std::vector< LODInfo > m_LODinfo
int m_numPatchesX = 0
int m_numPatchesZ = 0
LodManager m_LODManager
Detailed Description
Represents a terrain object.
Definition at line 30 of file terrain.h.
Constructor & Destructor Documentation
Terrain() [1/2]
Terrain::Terrain (float scaleX = 1.f, float scaleY = 1.f, float scaleZ = 1.f)
Constructs a Terrain object with default scale values.
Parameters
scaleX The scale factor along the X-axis.
scaleY The scale factor along the Y-axis.
scaleZ The scale factor along the Z-axis.
Definition at line 3 of file terrain.cpp.
: scaleX(scaleX), scaleY(scaleY), scaleZ(scaleZ), m_Width(0), m_Length(0), m_Size(0) {}
References m_Length, m_Size, m_Width, scaleX, scaleY, and scaleZ.
Terrain() [2/2]
Terrain::Terrain (std::string filename, int size, int patchSize, float zfar)
Constructs a Terrain object from a heightmap file.
Parameters
filename The filename of the heightmap file.
size The size of the terrain.
patchSize The size of a terrain patch.
zfar The far clipping plane for LOD calculation.
Definition at line 5 of file terrain.cpp.
{
    loadHeightMap(filename, size, patchSize, zfar);
}
References loadHeightMap().
~Terrain()
Terrain::~Terrain ()
Default destructor for Terrain.
Definition at line 10 of file terrain.cpp.
{}
Member Function Documentation
addFilter()
void Terrain::addFilter (std::vector< float > & terrainData, float weight) private
Adds a filter to the terrain data.
Parameters
terrainData The vector storing terrain data.
weight The weight of the filter.
Definition at line 531 of file terrain.cpp.
{
    // Erode left to right, starting from the beginning of each row
    for (int i = 0; i < m_Size; i++) {
        filterPass(&terrainData[m_Size * i], 1, weight);
    }
    // Erode right to left, starting from the end of each row
    for (int i = 0; i < m_Size; i++) {
        filterPass(&terrainData[m_Size * i + m_Size - 1], -1, weight);
    }
    // Erode top to bottom, starting from the beginning of each column
    for (int i = 0; i < m_Size; i++) {
        filterPass(&terrainData[i], m_Size, weight);
    }
    // Erode bottom to top, starting from the end of each column
    for (int i = 0; i < m_Size; i++) {
        filterPass(&terrainData[m_Size * (m_Size - 1) + i], -m_Size, weight);
    }
}
References m_Size.
addProceduralTexture()
bool Terrain::addProceduralTexture (const std::string & fileName)
Adds a procedural texture to the terrain.
Parameters
fileName The filename of the procedural texture file.
Returns
True if the procedural texture was added successfully, false otherwise.
Definition at line 647 of file terrain.cpp.
{
    return texGen.addTexture(fileName);
}
References TextureGenerator::addTexture(), and texGen.
Referenced by main().
AddTriangle()
unsigned int Terrain::AddTriangle (unsigned int Index, std::vector< unsigned int > & Indices, unsigned int v1, unsigned int v2, unsigned int v3) private
Adds a triangle to the index buffer.
Parameters
Index The current index in the index buffer.
Indices The vector storing indices.
v1 The index of vertex 1.
v2 The index of vertex 2.
v3 The index of vertex 3.
Returns
The updated index.
Definition at line 266 of file terrain.cpp.
{
    //std::cout << "Index: " << Index << " Size: " << Indices.size() << std::endl;
    assert(Index < Indices.size());
    Indices[Index++] = v1;
    assert(Index < Indices.size());
    Indices[Index++] = v2;
    assert(Index < Indices.size());
    Indices[Index++] = v3;
    return Index;
}
CalcLODNormals()
void Terrain::CalcLODNormals (std::vector< float > & Vertices, std::vector< unsigned int > & Indices) private
Calculates normals for the terrain based on vertices and indices.
Parameters
Vertices The vector storing vertex positions.
Indices The vector storing indices.
Definition at line 422 of file terrain.cpp.
{
    unsigned int Index = 0;
    int vertSize = 3;
    int texSize = 2;
    int normSize = 3;
    for (int z = 0; z < m_Length - 1; z += (m_patchSize - 1))
    {
        for (int x = 0; x < m_Width - 1; x += (m_patchSize - 1))
        {
            int baseVertex = z * m_Width + x;
            int numIndices = m_LODinfo[0].info[0][0][0][0].Count;;
            for (int i = 0; i < numIndices; i += 3)
            {
                unsigned int Index0 = baseVertex + Indices[i];
                unsigned int Index1 = baseVertex + Indices[i + 1];
                unsigned int Index2 = baseVertex + Indices[i + 2];
                glm::vec3 vec1 = glm::vec3(Vertices[(Index1 * 8)], Vertices[(Index1 * 8) + 1], Vertices[(Index1 * 8) + 2]) - glm::vec3(Vertices[(Index0 * 8)], Vertices[(Index0 * 8) + 1], Vertices[(Index0 * 8) + 2]);
                glm::vec3 vec2 = glm::vec3(Vertices[(Index2 * 8)], Vertices[(Index2 * 8) + 1], Vertices[(Index2 * 8) + 2]) - glm::vec3(Vertices[(Index0 * 8)], Vertices[(Index0 * 8) + 1], Vertices[(Index0 * 8) + 2]);
                glm::vec3 Normal = glm::cross(vec1, vec2);
                Normal = glm::normalize(Normal);
                Vertices[(Index0 * 8) + vertSize + texSize] += Normal.x;
                Vertices[(Index0 * 8) + vertSize + texSize + 1] += Normal.y;
                Vertices[(Index0 * 8) + vertSize + texSize + 2] += Normal.z;
                Vertices[(Index1 * 8) + vertSize + texSize] += Normal.x;
                Vertices[(Index1 * 8) + vertSize + texSize + 1] += Normal.y;
                Vertices[(Index1 * 8) + vertSize + texSize + 2] += Normal.z;
                Vertices[(Index2 * 8) + vertSize + texSize] += Normal.x;
                Vertices[(Index2 * 8) + vertSize + texSize + 1] += Normal.y;
                Vertices[(Index2 * 8) + vertSize + texSize + 2] += Normal.z;
            }
        }
    }
    for (int i = 0; i < Vertices.size() / 8; i ++)
    {
        glm::vec3 normal = glm::normalize(glm::vec3(Vertices[(i * 8) + vertSize + texSize], Vertices[(i * 8) + vertSize + texSize + 1], Vertices[(i * 8) + vertSize + texSize + 2]));
        Vertices[(i * 8) + vertSize + texSize] = normal.x;
        Vertices[(i * 8) + vertSize + texSize + 1] = normal.y;
        Vertices[(i * 8) + vertSize + texSize + 2] = normal.z;
        //std::cout << Vertices[(i * 8) + vertSize + texSize] << " " << Vertices[(i * 8) + vertSize + texSize + 1] << " " << Vertices[(i * 8) + vertSize + texSize + 2] << std::endl;
    }
}
References m_Length, m_patchSize, and m_Width.
CalcNormal()
glm::vec3 Terrain::CalcNormal (int x, int z) private
Calculates the normal at a specific position on the terrain.
Parameters
x The x-coordinate position.
z The z-coordinate position.
Returns
The normal vector.
Definition at line 724 of file terrain.cpp.
{
    float left;
    float right;
    float up;
    float down;
    if (x > 0)
    {
        left = m_Heights[(z * m_Width) + (x - 1)];
    }
    else
    {
        left = m_Heights[(z * m_Width) + x];
    }
    if (x < (m_Width - 1))
    {
        right = m_Heights[(z * m_Width) + (x + 1)];
    }
    else
    {
        right = m_Heights[(z * m_Width) + x];
    }
    if (z > 0)
    {
        up = m_Heights[((z - 1) * m_Width) + x];
    }
    else
    {
        up = m_Heights[(z * m_Width) + x];
    }
    if (z < (m_Length - 1))
    {
        down = m_Heights[((z + 1) * m_Width) + x];
    }
    else
    {
        down = m_Heights[(z * m_Width) + x];
    }
    glm::vec3 normal;
    normal.x = right - left;
    normal.y = 2.f;
    normal.z = down - up;
    glm::normalize(normal);
    return normal;
}
References m_Length, and m_Width.
calcNumIndices()
int Terrain::calcNumIndices () private
Calculates the number of indices.
Returns
The number of indices.
Definition at line 405 of file terrain.cpp.
{
    int NumQUADS = (m_patchSize - 1) * (m_patchSize - 1);
    int numIndices = 0;
    int MaxPermsPerLevel = 16;
    const int IndicesPerQUAD = 6;
    for (int LOD = 0; LOD <= m_maxLOD; LOD++)
    {
        numIndices += NumQUADS * IndicesPerQUAD * MaxPermsPerLevel;
        NumQUADS /= 4;
    }
    return numIndices;
}
References m_maxLOD, and m_patchSize.
Referenced by generateTerrainBuffers().
CreateGeomipmapGrid()
void Terrain::CreateGeomipmapGrid (int width, int depth, int patchSize, float zfar) private
Creates a geomipmap grid for the terrain.
Parameters
width The width of the terrain.
depth The depth of the terrain.
patchSize The size of a terrain patch.
zfar The far clipping plane for LOD calculation.
Definition at line 477 of file terrain.cpp.
{
    if ((width - 1) % (patchSize - 1) != 0) {
        int RecommendedWidth = ((width - 1 + patchSize - 1) / (patchSize - 1)) * (patchSize - 1) + 1;
        printf("Width minus 1 (%d) must be divisible by PatchSize minus 1 (%d)\n", width, patchSize);
        printf("Try using Width = %d\n", RecommendedWidth);
        exit(0);
    }
    if ((depth - 1) % (patchSize - 1) != 0) {
        int RecommendedDepth = ((depth - 1 + patchSize - 1) / (patchSize - 1)) * (patchSize - 1) + 1;
        printf("Depth minus 1 (%d) must be divisible by PatchSize minus 1 (%d)\n", depth, patchSize);
        printf("Try using Width = %d\n", RecommendedDepth);
        exit(0);
    }
    if (patchSize < 3) {
        printf("The minimum patch size is 3 (%d)\n", patchSize);
        exit(0);
    }
    if (patchSize % 2 == 0) {
        printf("Patch size must be an odd number (%d)\n", patchSize);
        exit(0);
    }
    m_Width = width;
    m_Length = depth;
    m_patchSize = patchSize;
    m_numPatchesX = (width - 1) / (patchSize - 1);
    m_numPatchesZ = (depth - 1) / (patchSize - 1);
    m_maxLOD = m_LODManager.initLodManager(patchSize, m_numPatchesX, m_numPatchesZ, zfar);
    m_LODinfo.resize(m_maxLOD + 1);
    generateTerrainBuffers();
}
References generateTerrainBuffers(), m_Length, m_numPatchesX, m_numPatchesZ, m_patchSize, and m_Width.
Referenced by genFaultFormation(), and loadHeightMap().
createProceduralTexture()
bool Terrain::createProceduralTexture (glm::vec3 ambient, glm::vec3 diffuse, glm::vec3 specular, float specEx)
Creates a procedural texture for the terrain.
Parameters
ambient The ambient color of the material.
diffuse The diffuse color of the material.
specular The specular color of the material.
specEx The specular exponent of the material.
Returns
True if the procedural texture was created successfully, false otherwise.
Definition at line 160 of file terrain.cpp.
{
    int size = m_Size - 1;
    if (m_Heights.empty() || texGen.getNumTextures() == 0)
    {
        return false;
    }
    unsigned char curHeight; //current height in the heightmap
    float weight; //weight of influence of tex to height
    //setup room for the new texture
    texGen.setupNewTexture(size, size);
    ImgRGB<unsigned char> color;
    ImgRGB<unsigned char> totalColor;
    float range = texGen.getRange();
    //loop through each point in the heightmap
    // and get height value
        for (int z = 0; z < size; z++) {
            for (int x = 0; x < size; x++) {
                totalColor.reset();
                curHeight = getHeight(x, z);
                //calculate the contribution from for each texture
                for (int i = 0; i < texGen.getNumTextures(); i++) {
                    weight = (range - abs((float)curHeight - texGen.getTextureMax(i))) / range;
                    if (weight > 0.0) {
                        unsigned int texX = x;
                        unsigned int texZ = z;
                        getTexCoord(i, texX, texZ);
                        color = texGen.getColor(i, texX, texZ);
                        totalColor.r += color.r * weight;
                        totalColor.g += color.g * weight;
                        totalColor.b += color.b * weight;
                    } // end if
                } // end for i
                //add the combined color to the new texture.
                texGen.setColor(x, z, totalColor);
                ambient.x += totalColor.r;
                ambient.y += totalColor.g;
                ambient.z += totalColor.b;
            } // end for x
        } // end for z
        //load the new texture into memory ready for use
        ambient.x = ambient.x / (size * size);
        ambient.y = ambient.y / (size * size);
        ambient.z = ambient.z / (size * size);
        material.SetTextureFile("terrain");
        material.SetAmbient(ambient);
        material.SetDiffuse(diffuse);
        material.SetSpecular(specular);
        material.SetSpecularExponent(specEx);
    TextureManager::GetInstance().CreateTexture(material.GetTexture(), texGen.getTex());
    return true;
}
References getHeight(), TextureGenerator::getNumTextures(), TextureGenerator::getRange(), getTexCoord(), TextureGenerator::getTextureMax(), m_Size, TextureGenerator::setupNewTexture(), and texGen.
createTriangeFan()
unsigned int Terrain::createTriangeFan (int Index, std::vector< unsigned int > & indices, int LODCore, int LODLeft, int LODRight, int LODTop, int LODBottom, int x, int z) private
Creates a triangle fan for a given patch.
Parameters
Index The current index in the index buffer.
indices The vector storing indices.
LODCore The level of detail for the core patch.
LODLeft The level of detail for the left patch.
LODRight The level of detail for the right patch.
LODTop The level of detail for the top patch.
LODBottom The level of detail for the bottom patch.
x The x-coordinate of the patch.
z The z-coordinate of the patch.
Returns
The number of indices.
Definition at line 342 of file terrain.cpp.
{
    int StepLeft = std::pow(2, LODLeft);
    int StepRight = std::pow(2, LODRight);
    int StepTop = std::pow(2, LODTop);
    int StepBottom = std::pow(2, LODBottom);
    int StepCenter = std::pow(2, LODCore);
    unsigned int IndexCenter = (z + StepCenter) * m_Width + x + StepCenter;
    unsigned int IndexTemp1 = z * m_Width + x;
    unsigned int IndexTemp2 = (z + StepLeft) * m_Width + x;
    Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    if (LODLeft == LODCore) {
        IndexTemp1 = IndexTemp2;
        IndexTemp2 += StepLeft * m_Width;
        Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    }
    IndexTemp1 = IndexTemp2;
    IndexTemp2 += StepTop;
    Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    if (LODTop == LODCore) {
        IndexTemp1 = IndexTemp2;
        IndexTemp2 += StepTop;
        Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    }
    IndexTemp1 = IndexTemp2;
    IndexTemp2 -= StepRight * m_Width;
    Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    if (LODRight == LODCore) {
        IndexTemp1 = IndexTemp2;
        IndexTemp2 -= StepRight * m_Width;
        Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    }
    IndexTemp1 = IndexTemp2;
    IndexTemp2 -= StepBottom;
    Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    if (LODBottom == LODCore) {
        IndexTemp1 = IndexTemp2;
        IndexTemp2 -= StepBottom;
        Index = AddTriangle(Index, indices, IndexCenter, IndexTemp1, IndexTemp2);
    }
    return Index;
}
References m_Width.
filterPass()
void Terrain::filterPass (float * startP, int increment, float weight) private
Applies a filter pass to the terrain data.
Parameters
startP Pointer to the start of the terrain data.
increment The increment for the filter pass.
weight The weight of the filter pass.
Definition at line 518 of file terrain.cpp.
{
    float yprev = *startP;
    int j = increment;
    float k = weight;
    for (int i = 1; i < m_Size; i++) {
        *(startP + j) = k * yprev + (1 - k) * (*(startP + j));
        yprev = *(startP + j);
        j += increment;
    }
}
References m_Size.
generateTerrainBuffers()
void Terrain::generateTerrainBuffers () private
Generates the vertex and index buffers for the terrain.
Definition at line 652 of file terrain.cpp.
{
    float texCoordScaleX = 1.0f / (m_Width - 1);
    float texCoordScaleZ = 1.0f / (m_Length - 1);
    float xNorm = 0.0f;
    float yNorm = 1.0f;
    float zNorm = 0.0f;
    // Generate terrain vertices and texture coordinates
    std::vector<float> vertices;
    for (int z = 0; z < m_Size; ++z) {
        for (int x = 0; x < m_Size; ++x) {
            float xPos = static_cast<float>(x);
            float zPos = static_cast<float>(z);
            float yPos = m_Heights[z * m_Size + x];
            // Vertex positions
            vertices.push_back(xPos * scaleX);
            vertices.push_back(yPos * scaleY);
            vertices.push_back(zPos * scaleZ);
            // Texture coordinates (mapping the entire terrain's extent)
            //float texCoordX = static_cast<float>(x) / static_cast<float>(m_Size - 1);
            //float texCoordY = static_cast<float>(z) / static_cast<float>(m_Size - 1);
            float texCoordX = xPos * texCoordScaleX;
            float texCoordY = zPos * texCoordScaleZ;
            texCoordX *= m_Width;
            texCoordY *= m_Length;
            vertices.push_back(texCoordX);
            vertices.push_back(texCoordY);
            glm::vec3 normal = CalcNormal(x, z);
            vertices.push_back(normal.x);
            vertices.push_back(normal.y);
            vertices.push_back(normal.z);
        }
    }
    // Generate terrain indices
    std::vector<unsigned int> indices;
    //int numQuads = (m_patchSize - 1) * (m_patchSize - 1);
    //indices.resize(numQuads * 6);
    int NumIndices = calcNumIndices();
    indices.resize(NumIndices);
    InitIndices(indices);
    // Setup vertex array
    VertexBufferLayout layout;
    layout.Push<float>(3); // Vertex positions
    layout.Push<float>(2); // Texture coordinates
    layout.Push<float>(3); // Normals
    CalcLODNormals(vertices, indices);
    // Create and bind index buffer
    m_IBO = std::make_unique<IndexBuffer>(indices.data(), indices.size());
    // Create and bind vertex buffer
    m_VBO = std::make_unique<VertexBuffer>(vertices.data(), vertices.size() * sizeof(float));
    m_VAO.AddBuffer(*m_VBO, layout);
}
References calcNumIndices(), m_Length, m_Size, and m_Width.
Referenced by CreateGeomipmapGrid().
genFaultFormation()
bool Terrain::genFaultFormation (int iterations, int hSize, int minHeight, int maxHeight, float weight, bool random, int patchSize, float zfar)
Generates a terrain using the fault formation algorithm.
Parameters
iterations The number of iterations for the algorithm.
hSize The size of the terrain.
minHeight The minimum height of the terrain.
maxHeight The maximum height of the terrain.
weight The weight parameter for the algorithm.
random Flag indicating whether to use random values.
patchSize The size of a terrain patch.
zfar The far clipping plane for LOD calculation.
Returns
True if the terrain was generated successfully, false otherwise.
Definition at line 583 of file terrain.cpp.
{
    int x1, x2, z1, z2;
    std::vector<float> data;
    int displacement;
    if (hSize <= 0) {
        return false;
    }
    if (random)
    {
        srand(static_cast<unsigned int>(time(NULL)));
    }
    m_Size = hSize;
    data.resize(m_Size * m_Size, 0);
    m_Heights.resize(m_Size * m_Size);
    // Generate heightfield
    for (int j = 0; j < iterations; j++) {
        // Calculate the displacement value for the current iteration
        displacement = maxHeight - ((maxHeight - minHeight) * j) / iterations;
        // Pick the first random point P1(x1, z1) from the height map
        x1 = (rand() % m_Size);
        z1 = (rand() % m_Size);
        // Pick up the second random point P2(x2, z2) and make sure it is different from the first point
        do {
            x2 = (rand() % m_Size);
            z2 = (rand() % m_Size);
        } while (x2 == x1 && z2 == z1);
        // For each point P(x, z) in the field, calculate the new height values
        for (int z = 0; z < m_Size; z++) {
            for (int x = 0; x < m_Size; x++) {
                // Determine which side of the line P1P2 the point P lies in
                if (((x - x1) * (z2 - z1) - (x2 - x1) * (z - z1)) > 0) {
                    data[(z * m_Size) + x] += static_cast<float>(displacement);
                }
            }
        }
        addFilter(data, weight);
    }
    // Normalise the heightfield
    normaliseTerrain(data);
    // Copy the float heightfield to terrainData (in unsigned char)
    for (int z = 0; z < m_Size; z++) {
        for (int x = 0; x < m_Size; x++) {
            setHeightAtPoint(data[(z * m_Size) + x], x, z);
        }
    }
    m_Heights = data;
    CreateGeomipmapGrid(m_Size, m_Size, patchSize, zfar);
    return true;
}
References CreateGeomipmapGrid(), and m_Size.
getHeight()
float Terrain::getHeight (int xpos, int zpos)
Gets the height at a specific position on the terrain.
Parameters
xpos The x-coordinate position.
zpos The z-coordinate position.
Returns
The height at the specified position.
Definition at line 59 of file terrain.cpp.
{
    if (inbounds(xpos, zpos)) {
        return ((float)(m_Heights[(zpos * m_Size) + xpos]));
    }
    return 0.0f;
}
References inbounds().
Referenced by createProceduralTexture().
getSize()
const int Terrain::getSize () const
Gets the size of the terrain.
Returns
The size of the terrain.
Definition at line 67 of file terrain.cpp.
{
    return m_Size;
}
References m_Size.
getTexCoord()
void Terrain::getTexCoord (int texNum, unsigned int & x, unsigned int & y) private
Calculates the texture coordinates for a given texture number.
Parameters
texNum The texture number.
x The x-coordinate of the texture coordinate.
y The y-coordinate of the texture coordinate.
Definition at line 231 of file terrain.cpp.
{
    unsigned int height = texGen.getTexHeight(texNum);
    unsigned int width = texGen.getTexWidth(texNum);
    int repeatX = -1; // number of repeats in X direction
    int repeatY = -1; // number of repeats in Y direction
    int i = 0;
    // loop until we figure out how many times the tile
    // has repeated (on the X axis)
    while (repeatX == -1) {
        i++;
        //if x is less than the total width, found
        if (x < (width * i)) {
            repeatX = i - 1;
        }
    }
    // loop until we figure out how many times the tile
    // has repeated (on the Y axis)
    i = 0;
    while (repeatY == -1) {
        i++;
        //if y is less than the total height good
        if (y < (height * i)) {
            repeatY = i - 1;
        }
    }
    // update the given texture coordinates
    x = x - (width * repeatX);
    y = y - (height * repeatY);
}
References TextureGenerator::getTexHeight(), TextureGenerator::getTexWidth(), and texGen.
Referenced by createProceduralTexture().
inbounds()
bool Terrain::inbounds (int xpos, int zpos) private
Checks if a position is within the bounds of the terrain.
Parameters
xpos The x-coordinate position.
zpos The z-coordinate position.
Returns
True if the position is within bounds, false otherwise.
Definition at line 226 of file terrain.cpp.
{
    return (xpos >= 0 && xpos < m_Size && zpos >= 0 && zpos < m_Size);
}
References m_Size.
Referenced by getHeight(), and setHeightAtPoint().
InitIndices()
int Terrain::InitIndices (std::vector< unsigned int > & Indices) private
Initializes the index buffer.
Parameters
Indices The vector storing indices.
Returns
The number of indices.
Definition at line 279 of file terrain.cpp.
{
    int Index = 0;
    for (int LOD = 0; LOD <= m_maxLOD; LOD++)
    {
        Index = InitIndicesLOD(Index, Indices, LOD);
    }
    return Index;
}
References m_maxLOD.
InitIndicesLOD()
int Terrain::InitIndicesLOD (int Index, std::vector< unsigned int > & indices, int LOD) private
Initializes the index buffer for a given level of detail.
Parameters
Index The current index in the index buffer.
indices The vector storing indices.
LOD The level of detail.
Returns
The number of indices.
Definition at line 293 of file terrain.cpp.
{
    int TotalIndicesForLOD = 0;
    for (int l = 0; l < LEFT; l++)
    {
        for (int r = 0; r < RIGHT; r++)
        {
            for (int t = 0; t < TOP; t++)
            {
                for (int b = 0; b < BOTTOM; b++)
                {
                    m_LODinfo[LOD].info[l][r][t][b].Start = Index;
                    Index = InitIndicesLODSingle(Index, indices, LOD, LOD + l, LOD + r, LOD + t, LOD + b);
                    m_LODinfo[LOD].info[l][r][t][b].Count = Index - m_LODinfo[LOD].info[l][r][t][b].Start;
                    //TotalIndicesForLOD += m_LODinfo[LOD].info[l][r][t][b].Count;
                }
            }
        }
    }
    return Index;
}
InitIndicesLODSingle()
int Terrain::InitIndicesLODSingle (int Index, std::vector< unsigned int > & indices, int LODCore, int LODLeft, int LODRight, int LODTop, int LODBottom) private
Initializes the index buffer for a given level of detail (single patch).
Parameters
Index The current index in the index buffer.
indices The vector storing indices.
LODCore The level of detail for the core patch.
LODLeft The level of detail for the left patch.
LODRight The level of detail for the right patch.
LODTop The level of detail for the top patch.
LODBottom The level of detail for the bottom patch.
Returns
The number of indices.
Definition at line 319 of file terrain.cpp.
{
    int fanStep = std::pow(2, LODCore + 1);
    int EndPos = m_patchSize - 1 - fanStep;
    for (int z = 0; z <= EndPos; z += fanStep)
    {
        for (int x = 0; x <= EndPos; x += fanStep)
        {
            int lLeft = x == 0 ? LODLeft : LODCore;
            int lRight = x == EndPos ? LODRight : LODCore;
            int lBottom = x == 0 ? LODBottom : LODCore;
            int lTop = x == EndPos ? LODTop : LODCore;
            Index = createTriangeFan(Index, indices, LODCore, lLeft, lRight, lTop, lBottom, x, z);
        }
    }
    return Index;
}
References m_patchSize.
loadDetailMapTexture()
void Terrain::loadDetailMapTexture (const std::string & fileName)
Loads a detail map texture for the terrain.
Parameters
fileName The filename of the detail map texture file.
Definition at line 53 of file terrain.cpp.
{
    detailMapTextureFile = fileName;
    TextureManager::GetInstance().LoadTexture(fileName);
}
References detailMapTextureFile, TextureManager::GetInstance(), and TextureManager::LoadTexture().
Referenced by main().
loadHeightMap()
bool Terrain::loadHeightMap (const std::string & fileName, const int size, int patchSize, float zfar)
Loads a heightmap from a file.
Parameters
fileName The filename of the heightmap file.
size The size of the terrain.
patchSize The size of a terrain patch.
zfar The far clipping plane for LOD calculation.
Returns
True if the heightmap was loaded successfully, false otherwise.
Definition at line 12 of file terrain.cpp.
{
    std::ifstream file(fileName, std::ios::binary);
    if (!file.is_open()) {
        std::cerr << "Failed to open heightmap file: " << fileName << std::endl;
        return false;
    }
    m_Size = size;
    m_Width = size;
    m_Length = size;
    m_Heights.resize(size * size);
    //file.read(reinterpret_cast<char*>(m_Heights.data()), size * size * sizeof(float));
    // Read heightmap data
    for (int i = 0; i < size * size; ++i) {
        unsigned char height;
        file.read(reinterpret_cast<char*>(&height), sizeof(unsigned char));
        m_Heights[i] = static_cast<float>(height);
    }
    file.close();
    CreateGeomipmapGrid(m_Width, m_Length, patchSize, zfar);
    return true;
}
References CreateGeomipmapGrid(), m_Length, m_Size, and m_Width.
Referenced by main(), and Terrain().
loadTerrainTexture()
void Terrain::loadTerrainTexture (const std::string & fileName, glm::vec3 ambient, glm::vec3 diffuse, glm::vec3 specular, float specEx)
Loads a texture for the terrain.
Parameters
fileName The filename of the texture file.
ambient The ambient color of the material.
diffuse The diffuse color of the material.
specular The specular color of the material.
specEx The specular exponent of the material.
Definition at line 42 of file terrain.cpp.
{
    material.SetTextureFile(fileName);
    material.SetAmbient(ambient);
    material.SetDiffuse(diffuse);
    material.SetSpecular(specular);
    material.SetSpecularExponent(specEx);
    TextureManager::GetInstance().LoadTexture(fileName);
}
References TextureManager::GetInstance(), and TextureManager::LoadTexture().
normaliseTerrain()
void Terrain::normaliseTerrain (std::vector< float > & terrainData) private
Normalizes the terrain data.
Parameters
terrainData The vector storing terrain data.
Definition at line 554 of file terrain.cpp.
{
    float fMin = terrainData[0];
    float fMax = terrainData[0];
    float fHeight;
    // Find the min and max values of the height terrainData
    for (int i = 1; i < m_Size * m_Size; i++) {
        if (terrainData[i] > fMax) {
            fMax = terrainData[i];
        }
        else if (terrainData[i] < fMin) {
            fMin = terrainData[i];
        }
    }
    // Find the range of the altitude
    if (fMax <= fMin) {
        return;
    }
    fHeight = fMax - fMin;
    // Scale the values to a range of 0-255
    for (int i = 0; i < m_Size * m_Size; i++) {
        terrainData[i] = ((terrainData[i] - fMin) / fHeight) * 255.0f;
    }
}
References m_Size.
render()
void Terrain::render (const Renderer & renderer, Shader & shader, const glm::mat4 & viewMatrix, const glm::mat4 & projectionMatrix, glm::vec3 CameraPosition)
Renders the terrain.
Parameters
renderer The renderer used for rendering.
shader The shader used for rendering.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
CameraPosition The position of the camera.
Definition at line 72 of file terrain.cpp.
{
    MeshRenderer rend;
    Transform trans(glm::vec3(0, 0, 0), glm::vec3(0, 0, 0), glm::vec3(0, 1, 0));
    rend.UpdateWorldMatrix(trans);
    glm::mat4 mvpMatrix = projectionMatrix * viewMatrix;
    glm::vec2 terrainSize = glm::vec2(m_Width, m_Length);
    m_LODManager.UpdateLOD(CameraPosition);
    shader.Bind();
    // Set uniform matrices
    shader.SetUniformMat4f("u_MVP", mvpMatrix);
    shader.SetUniform2f("terrainSize", terrainSize);
    // Set lighting uniforms
    LightingManager::SetLightingUniforms(shader, rend.GetWorldMatrix());
    shader.SetUniform1i("u_IsLight", LightingManager::GetIsDirLight());
    // Set camera pos uniform
    glm::vec3 cameraPosition = glm::vec3(glm::inverse(viewMatrix)[3]);
    glm::vec4 cameraPositionVec4 = { cameraPosition, 1.0f };
    glm::vec4 localCamPosVec4 = cameraPositionVec4 * glm::vec4(0, 0, 0, 0);
    glm::vec3 localCamPos = { localCamPosVec4.x, localCamPosVec4.y, localCamPosVec4.z };
    shader.SetUniform3f("u_LocalCamPos", localCamPos);
    // Set material properties
    //shader.SetUniform4f("u_AmbientColour", { material.GetAmbient(), 1.0f });
    shader.SetUniform4f("u_AmbientColour", glm::vec4(material.GetDiffuse(), 1));
    shader.SetUniform4f("u_DiffuseColour", glm::vec4(material.GetDiffuse(), 1));
    shader.SetUniform4f("u_SpecularColour", glm::vec4(material.GetSpecular(), 1));
    shader.SetUniform1f("u_SpecularExponent", material.GetSpecularExponent());
    if (!material.GetTexture().empty()) {
        TextureManager::GetInstance().SetActiveTexture(material.GetTexture(), TextureType::DEFAULT, 0);
        shader.SetUniform1i("u_Texture1", 0);
        shader.SetUniform1f("u_TextureSet", 1);
    }
    else
    {
        shader.SetUniform1f("u_TextureSet", 0);
    }
    if (!detailMapTextureFile.empty()) {
        TextureManager::GetInstance().SetActiveTexture(detailMapTextureFile, TextureType::DEFAULT, 1);
        shader.SetUniform1i("u_Texture2", 1);
    }
    float PatchSize = ((float)m_patchSize - 1.0f) * 1;
    float halfPatchSize = PatchSize / 2;
    std::vector<int> baseVertexGroup;
    std::vector<size_t> baseIndiceGroup;
    for (int PatchZ = 0; PatchZ < m_numPatchesZ; PatchZ++)
    {
        for (int PatchX = 0; PatchX < m_numPatchesX; PatchX++)
        {
            int z = PatchZ * (m_patchSize - 1);
            int x = PatchX * (m_patchSize - 1);
            const LodManager::patchLod& PLOD = m_LODManager.getPatchLod(PatchX, PatchZ);
            int C = PLOD.Core;
            int L = PLOD.Left;
            int R = PLOD.Right;
            int T = PLOD.Top;
            int B = PLOD.Bottom;
            size_t baseIndex = sizeof(unsigned int) * m_LODinfo[C].info[L][R][T][B].Start;
            int baseVertex = z * m_Width + x;
            baseIndiceGroup.push_back(baseIndex);
            renderer.TerrainRender(m_VAO, *m_IBO, shader, GraphicsEnum::TRIANGLES, m_LODinfo[C].info[L][R][T][B].Count, GraphicsEnum::UNSIGNED_INT, (void*)baseIndex, baseVertex);
        }
    }
    TextureManager::GetInstance().Unbind();
    shader.Unbind();
}
References Shader::Bind(), LodManager::patchLod::Bottom, LodManager::patchLod::Core, DEFAULT, detailMapTextureFile, TextureManager::GetInstance(), LightingManager::GetIsDirLight(), LodManager::patchLod::Left, m_numPatchesX, m_numPatchesZ, m_patchSize, m_Width, LodManager::patchLod::Right, TextureManager::SetActiveTexture(), Shader::SetUniform1f(), Shader::SetUniform1i(), LodManager::patchLod::Top, Shader::Unbind(), TextureManager::Unbind(), and MeshRenderer::UpdateWorldMatrix().
setHeightAtPoint()
void Terrain::setHeightAtPoint (float height, int xpos, int zpos)
Sets the height at a specific position on the terrain.
Parameters
height The height value to set.
xpos The x-coordinate position.
zpos The z-coordinate position.
Definition at line 218 of file terrain.cpp.
{
    if (inbounds(xpos, zpos))
    {
        m_Heights[zpos * m_Size + xpos] = height;
    }
}
References inbounds().
Member Data Documentation
detailMapTextureFile
std::string Terrain::detailMapTextureFile private
The filename of the detail map texture.
Definition at line 155 of file terrain.h.
Referenced by loadDetailMapTexture(), and render().
m_Heights
std::vector<float> Terrain::m_Heights private
The heights of the terrain vertices.
Definition at line 148 of file terrain.h.
m_IBO
std::unique_ptr<IndexBuffer> Terrain::m_IBO private
The Index Buffer Object for storing indices.
Definition at line 159 of file terrain.h.
m_Length
unsigned int Terrain::m_Length private
The length of the terrain.
Definition at line 146 of file terrain.h.
Referenced by CalcLODNormals(), CalcNormal(), CreateGeomipmapGrid(), generateTerrainBuffers(), loadHeightMap(), and Terrain().
m_LODinfo
std::vector<LODInfo> Terrain::m_LODinfo private
Vector storing information about LODs.
Definition at line 181 of file terrain.h.
m_LODManager
LodManager Terrain::m_LODManager private
The LOD manager for managing level of detail.
Definition at line 185 of file terrain.h.
m_maxLOD
int Terrain::m_maxLOD private
The maximum level of detail for the terrain.
Definition at line 164 of file terrain.h.
Referenced by calcNumIndices(), and InitIndices().
m_numPatchesX
int Terrain::m_numPatchesX = 0 private
Number of patches in the x-direction.
Definition at line 182 of file terrain.h.
Referenced by CreateGeomipmapGrid(), and render().
m_numPatchesZ
int Terrain::m_numPatchesZ = 0 private
Number of patches in the z-direction.
Definition at line 183 of file terrain.h.
Referenced by CreateGeomipmapGrid(), and render().
m_patchSize
int Terrain::m_patchSize private
The size of a terrain patch.
Definition at line 163 of file terrain.h.
Referenced by CalcLODNormals(), calcNumIndices(), CreateGeomipmapGrid(), InitIndicesLODSingle(), and render().
m_Size
int Terrain::m_Size private
The size of the terrain.
Definition at line 144 of file terrain.h.
Referenced by addFilter(), createProceduralTexture(), filterPass(), generateTerrainBuffers(), genFaultFormation(), getSize(), inbounds(), loadHeightMap(), normaliseTerrain(), and Terrain().
m_VAO
VertexArray Terrain::m_VAO private
The Vertex Array Object for rendering.
Definition at line 157 of file terrain.h.
m_VBO
std::unique_ptr<VertexBuffer> Terrain::m_VBO private
The Vertex Buffer Object for storing vertex data.
Definition at line 158 of file terrain.h.
m_Width
unsigned int Terrain::m_Width private
The width of the terrain.
Definition at line 145 of file terrain.h.
Referenced by CalcLODNormals(), CalcNormal(), CreateGeomipmapGrid(), createTriangeFan(), generateTerrainBuffers(), loadHeightMap(), render(), and Terrain().
material
Material Terrain::material private
The material used for rendering the terrain.
Definition at line 161 of file terrain.h.
scaleX
float Terrain::scaleX private
The scaling factor in the x-axis.
Definition at line 149 of file terrain.h.
Referenced by Terrain().
scaleY
float Terrain::scaleY private
The scaling factor in the y-axis.
Definition at line 150 of file terrain.h.
Referenced by Terrain().
scaleZ
float Terrain::scaleZ private
The scaling factor in the z-axis.
Definition at line 151 of file terrain.h.
Referenced by Terrain().
terrainTextureFile
std::string Terrain::terrainTextureFile private
The filename of the terrain texture.
Definition at line 154 of file terrain.h.
texGen
TextureGenerator Terrain::texGen private
The texture generator used for procedural textures.
Definition at line 153 of file terrain.h.
Referenced by addProceduralTexture(), createProceduralTexture(), and getTexCoord().
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/terrain.h
AAAAGameEngine2/AAAAGameEngine2/src/terrain.cpp