AAAAEngine: VertexArray Class Reference
VertexArray Class Reference
A class representing a Vertex Array Object (VAO) in OpenGL.
#include <VertexArray.h>
Public Member Functions
VertexArray ()
Constructor for the VertexArray class.
~VertexArray ()
Destructor for the VertexArray class.
void AddBuffer (const VertexBuffer &vb, const VertexBufferLayout &layout)
Add a vertex buffer and layout to the Vertex Array Object (VAO).
void Bind () const
Bind the Vertex Array Object (VAO) for rendering.
void Unbind () const
Unbind the currently bound Vertex Array Object (VAO).
Private Attributes
unsigned int m_RenderedID
Detailed Description
A class representing a Vertex Array Object (VAO) in OpenGL.
Definition at line 12 of file VertexArray.h.
Constructor & Destructor Documentation
VertexArray()
VertexArray::VertexArray ()
Constructor for the VertexArray class.
Definition at line 3 of file VertexArray.cpp.
                         : m_RenderedID(0)
{
    GraphicsUtility::GenerateVertexArrays(1, &m_RenderedID);
}
References m_RenderedID.
~VertexArray()
VertexArray::~VertexArray ()
Destructor for the VertexArray class.
Definition at line 8 of file VertexArray.cpp.
{
    GraphicsUtility::DeleteVertexArrays(1, &m_RenderedID);
}
Member Function Documentation
AddBuffer()
void VertexArray::AddBuffer (const VertexBuffer & vb, const VertexBufferLayout & layout)
Add a vertex buffer and layout to the Vertex Array Object (VAO).
Parameters
vb The VertexBuffer to add.
layout The VertexBufferLayout to specify the layout of the data in the VertexBuffer.
Definition at line 13 of file VertexArray.cpp.
{
    Bind();
    vb.Bind();
    const auto& elements = layout.GetElements();
    unsigned int offset = 0;
    for (int i = 0; i < elements.size(); i++)
    {
        const auto& element = elements[i];
        // Define the vertex attribute pointer
        GraphicsUtility::EnableVertexAttribArray(i);
        GraphicsUtility::VertexAttribPointer(i, element.count, element.type, element.normalized, layout.GetStride(), (const void*)offset);
        offset += element.count * VertexBufferElement::GetSizeOfType(element.type);
    }
}
References Bind(), and VertexBuffer::Bind().
Bind()
void VertexArray::Bind () const
Bind the Vertex Array Object (VAO) for rendering.
Definition at line 29 of file VertexArray.cpp.
{
    GraphicsUtility::BindVertexArray(m_RenderedID);
}
References GraphicsUtility::BindVertexArray(), and m_RenderedID.
Referenced by AddBuffer(), Renderer::Render(), and Renderer::TerrainRender().
Unbind()
void VertexArray::Unbind () const
Unbind the currently bound Vertex Array Object (VAO).
Definition at line 34 of file VertexArray.cpp.
{
    GraphicsUtility::BindVertexArray(0);
}
References GraphicsUtility::BindVertexArray().
Member Data Documentation
m_RenderedID
unsigned int VertexArray::m_RenderedID private
The OpenGL identifier for the Vertex Array Object (VAO).
Definition at line 14 of file VertexArray.h.
Referenced by Bind(), and VertexArray().
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/VertexArray.h
AAAAGameEngine2/AAAAGameEngine2/src/VertexArray.cpp