AAAAEngine: TextureManager Class Reference
TextureManager Class Reference
A class for managing textures in OpenGL.
#include <TextureManager.h>
Public Member Functions
TextureManager (const TextureManager &)=delete
TextureManager & operator= (const TextureManager &)=delete
~TextureManager ()
Destructor to clean up resources.
unsigned int updateTexture (const std::string &path)
Updates an existing texture.
unsigned int LoadTexture (const std::string &path, TextureType type=TextureType::DEFAULT)
Loads a texture from the specified file path.
unsigned int LoadTexture (const std::vector< std::string > &paths, TextureType type=TextureType::CUBEMAP)
Loads a cubemap texture from the specified file paths.
unsigned int CreateTexture (const std::string &name, Image &image)
Creates a new OpenGL texture from the provided image data.
unsigned int GetTexture (const std::string &path) const
Get texture ID by its path.
void Bind (const unsigned int id, TextureType type=TextureType::DEFAULT, int slot=0) const
Binds the texture correlating to id.
void Unbind () const
void SetActiveTexture (const std::string &path, TextureType type=TextureType::DEFAULT, int slot=0) const
Activate a texture for rendering. This function binds and enables the specified texture.
void DeleteAllTextures ()
Delete all textures managed by the TextureManager.
Static Public Member Functions
static TextureManager & GetInstance ()
Get the singleton instance of TextureManager.
Private Member Functions
TextureManager ()
Private constructor to enforce singleton pattern.
Private Attributes
std::unordered_map< std::string, unsigned int > m_Textures
Detailed Description
A class for managing textures in OpenGL.
Definition at line 22 of file TextureManager.h.
Constructor & Destructor Documentation
TextureManager() [1/2]
TextureManager::TextureManager () inline private
Private constructor to enforce singleton pattern.
Definition at line 29 of file TextureManager.h.
{}
TextureManager() [2/2]
TextureManager::TextureManager (const TextureManager &) delete
~TextureManager()
TextureManager::~TextureManager ()
Destructor to clean up resources.
Definition at line 3 of file TextureManager.cpp.
{
    DeleteAllTextures();
}
References DeleteAllTextures().
Member Function Documentation
Bind()
void TextureManager::Bind (const unsigned int id, TextureType type = TextureType::DEFAULT, int slot = 0) const
Binds the texture correlating to id.
Parameters
id The id of the texture to bind.
Definition at line 211 of file TextureManager.cpp.
{
    if (id != 0) {
        switch (type) {
        case TextureType::DEFAULT:
            glActiveTexture(GL_TEXTURE0 + slot); // Activate the texture slot
            GraphicsUtility::Enable(GraphicsEnum::TEXTURE_2D);
            GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_2D, id);
            break;
        case TextureType::CUBEMAP:
            glActiveTexture(GL_TEXTURE0 + slot); // Activate the texture slot
            GraphicsUtility::Enable(GraphicsEnum::TEXTURE_CUBE_MAP);
            GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_CUBE_MAP, id);
            break;
        }
    }
}
Referenced by Skybox::Render().
CreateTexture()
unsigned int TextureManager::CreateTexture (const std::string & name, Image & image)
Creates a new OpenGL texture from the provided image data.
Parameters
name The name to associate with the created texture.
image The image data used to create the texture.
Returns
The ID of the created texture.
Definition at line 165 of file TextureManager.cpp.
{
    // Check if the texture is already loaded
    auto it = m_Textures.find(name);
    if (it != m_Textures.end()) {
        // Texture already loaded, return its ID
        return it->second;
    }
    unsigned int textureID;
    glGenTextures(1, &textureID);
    glBindTexture(GL_TEXTURE_2D, textureID);
    // Set texture parameters
    GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_WRAP_T, GraphicsEnum::REPEAT);
    GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_WRAP_T, GraphicsEnum::CLAMP_TO_EDGE);
    GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_WRAP_S, GraphicsEnum::REPEAT);
    GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_WRAP_S, GraphicsEnum::CLAMP_TO_EDGE);
    GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_MAG_FILTER, GraphicsEnum::LINEAR);
    GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_MIN_FILTER, GraphicsEnum::LINEAR_MIPMAP_LINEAR);
    GLenum format = (image.getBPP() == 4) ? GraphicsEnum::RGBA : GraphicsEnum::RGB;
    GraphicsUtility::TexImage2D(GraphicsEnum::TEXTURE_2D, 0, format, image.getHeight(), image.getWidth(), 0, format, GraphicsEnum::UNSIGNED_BYTE, image.getBuffer());
    // Generate mipmaps
    GraphicsUtility::GenerateMipMap(GraphicsEnum::TEXTURE_2D);
    GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_2D, 0);
    // Store texture ID in the map
    m_Textures[name] = textureID;
    return textureID;
}
DeleteAllTextures()
void TextureManager::DeleteAllTextures ()
Delete all textures managed by the TextureManager.
Definition at line 253 of file TextureManager.cpp.
{
    for (auto& pair : m_Textures) {
        GraphicsUtility::DeleteTextures(1, &pair.second);
    }
    m_Textures.clear();
}
Referenced by ~TextureManager().
GetInstance()
TextureManager & TextureManager::GetInstance () static
Get the singleton instance of TextureManager.
Returns
Reference to the TextureManager instance.
Definition at line 8 of file TextureManager.cpp.
{
    static TextureManager instance;
    return instance;
}
Referenced by UI::drawImage(), Terrain::loadDetailMapTexture(), Terrain::loadTerrainTexture(), Skybox::Render(), and Terrain::render().
GetTexture()
unsigned int TextureManager::GetTexture (const std::string & path) const
Get texture ID by its path.
Parameters
path The path of the texture.
Returns
The ID of the texture, or 0 if not found.
Definition at line 202 of file TextureManager.cpp.
{
    auto it = m_Textures.find(path);
    if (it != m_Textures.end()) {
        return it->second;
    }
    return 0; // Texture not found
}
Referenced by UI::drawImage(), and SetActiveTexture().
LoadTexture() [1/2]
unsigned int TextureManager::LoadTexture (const std::string & path, TextureType type = TextureType::DEFAULT)
Loads a texture from the specified file path.
Parameters
path The file path of the texture.
type The type of the texture (default: TextureType::DEFAULT).
Returns
The ID of the loaded texture.
Definition at line 31 of file TextureManager.cpp.
{
    // Check if the texture is already loaded
    auto it = m_Textures.find(path);
    if (it != m_Textures.end()) {
        // Texture already loaded, return its ID
        return it->second;
    }
    unsigned int textureID;
    GLenum textureTarget;
    if (type == TextureType::CUBEMAP) {
        // Handle loading of cube map
        std::cerr << "Cannot load a cube map from a single image path." << std::endl;
        return 0;
    }
    else {
        // Regular 2D texture
        textureTarget = GraphicsEnum::TEXTURE_2D;
        GraphicsUtility::GenTextures(1, &textureID);
        GraphicsUtility::BindTexture(textureTarget, textureID);
        // Set texture parameters
        GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_MIN_FILTER, GraphicsEnum::LINEAR);
        GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_MAG_FILTER, GraphicsEnum::LINEAR);
        GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_WRAP_S, GraphicsEnum::REPEAT);
        GraphicsUtility::TexParameteri(GraphicsEnum::TEXTURE_2D, GraphicsEnum::TEXTURE_WRAP_T, GraphicsEnum::REPEAT);
        Image image(path);
        GLenum format = (image.getBPP() == 4) ? GraphicsEnum::RGBA : GraphicsEnum::RGB;
        GraphicsUtility::TexImage2D(GraphicsEnum::TEXTURE_2D, 0, format, image.getHeight(), image.getWidth(), 0, format, GraphicsEnum::UNSIGNED_BYTE, image.getBuffer());
        GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_2D, 0);
    }
    // Store texture ID in the map
    m_Textures[path] = textureID;
    return textureID;
}
References CUBEMAP, and Image::Image().
Referenced by Terrain::loadDetailMapTexture(), and Terrain::loadTerrainTexture().
LoadTexture() [2/2]
unsigned int TextureManager::LoadTexture (const std::vector< std::string > & paths, TextureType type = TextureType::CUBEMAP)
Loads a cubemap texture from the specified file paths.
Parameters
paths The file paths of the cubemap textures.
type The type of the texture (default: TextureType::CUBEMAP).
Returns
The ID of the loaded cubemap texture.
Definition at line 72 of file TextureManager.cpp.
{
    // Check if the texture is already loaded
    auto it = m_Textures.find(paths[0]);
    if (it != m_Textures.end()) {
        // Texture already loaded, return its ID
        return it->second;
    }
    if (type != TextureType::CUBEMAP) {
        std::cerr << "Invalid texture type for loading a cube map." << std::endl;
        return 0;
    }
    unsigned int textureID;
    GraphicsUtility::GenTextures(1, &textureID);
    GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_CUBE_MAP, textureID);
    GraphicsUtility::TexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    GraphicsUtility::TexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    GraphicsUtility::TexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    GraphicsUtility::TexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    GraphicsUtility::TexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
    // Load and bind each face of the cubemap
    for (size_t i = 0; i < 6; ++i) {
        Image image(paths[i]);
        if (image.getWidth() == 0 || image.getHeight() == 0) {
            std::cerr << "Failed to load cubemap face: " << paths[i] << std::endl;
            continue; // Skip this face if loading fails
        }
        GLenum format = (image.getBPP() == 4) ? GL_RGBA : GL_RGB;
        GraphicsUtility::TexImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, format, image.getWidth(), image.getHeight(), 0, format, GL_UNSIGNED_BYTE, image.getBuffer());
    }
    // Unbind texture
    glBindTexture(GL_TEXTURE_CUBE_MAP, 0);
    // Store texture ID in the map
    m_Textures[paths[0]] = textureID;
    return textureID;
}
References CUBEMAP, Image::getHeight(), and Image::getWidth().
operator=()
TextureManager & TextureManager::operator= (const TextureManager &) delete
SetActiveTexture()
void TextureManager::SetActiveTexture (const std::string & path, TextureType type = TextureType::DEFAULT, int slot = 0) const
Activate a texture for rendering. This function binds and enables the specified texture.
Parameters
path The path of the texture to activate.
Definition at line 234 of file TextureManager.cpp.
{
    unsigned int textureID = GetTexture(path);
    if (textureID != 0) {
        switch (type) {
        case TextureType::DEFAULT:
            glActiveTexture(GL_TEXTURE0 + slot);
            GraphicsUtility::Enable(GraphicsEnum::TEXTURE_2D);
            GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_2D, textureID);
            break;
        case TextureType::CUBEMAP:
            glActiveTexture(GL_TEXTURE0 + slot);
            GraphicsUtility::Enable(GraphicsEnum::TEXTURE_CUBE_MAP);
            GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_CUBE_MAP, textureID);
            break;
        }
    }
}
References GetTexture().
Referenced by UI::drawImage(), and Terrain::render().
Unbind()
void TextureManager::Unbind () const
Definition at line 229 of file TextureManager.cpp.
{
    glBindTexture(GL_TEXTURE_2D, 0);
}
Referenced by UI::drawImage(), Skybox::Render(), and Terrain::render().
updateTexture()
unsigned int TextureManager::updateTexture (const std::string & path)
Updates an existing texture.
Parameters
path The file path of the texture to update.
Returns
The ID of the updated texture.
Definition at line 14 of file TextureManager.cpp.
{
    auto it = m_Textures.find(path);
    /*if (it != m_Textures.end()) {
        // Texture already loaded, return its ID
        return it->second;
    }*/
    Image image(path);
    GraphicsUtility::BindTexture(GraphicsEnum::TEXTURE_2D, m_Textures[path]);
    glTexSubImage2D(GraphicsEnum::TEXTURE_2D, 0, 0, 0, image.getWidth(), image.getHeight(), GL_RGB, GL_UNSIGNED_BYTE, image.getBuffer());
    return 0;
}
References Image::Image().
Member Data Documentation
m_Textures
std::unordered_map<std::string, unsigned int> TextureManager::m_Textures private
Map to store textures
Definition at line 24 of file TextureManager.h.
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/TextureManager.h
AAAAGameEngine2/AAAAGameEngine2/src/TextureManager.cpp