AAAAEngine: Shader Class Reference
Shader Class Reference
A class responsible for loading, compiling, and managing shader programs.
#include <Shader.h>
Public Member Functions
Shader (const std::string &filepath)
Construct a shader object and load shader source code from a file.
~Shader ()
Destructor to clean up shader resources.
void Bind () const
Bind the shader for rendering.
void Unbind () const
Unbind the shader.
void SetUniform1i (const std::string &name, int value)
Set an integer uniform in the shader program.
void SetUniform1f (const std::string &name, float value)
Set a floating-point uniform in the shader program.
void SetUniform1fv (const std::string &name, unsigned int size, float *values)
void SetUniform2f (const std::string &name, const glm::vec2 &value)
Set a 2-component floating point uniform in the shader program.
void SetUniform3f (const std::string &name, const glm::vec3 &value)
Set a 3-component floating point uniform in the shader program.
void SetUniform3fv (const std::string &name, unsigned int size, const std::vector< glm::vec3 > &value)
void SetUniform4f (const std::string &name, const glm::vec4 &value)
Set a 4-component floating point uniform in the shader program.
void SetUniform4fv (const std::string &name, unsigned int size, const std::vector< glm::vec4 > &value)
void SetUniformMat3f (const std::string &name, const glm::mat3 &matrix)
Set a 3x3 matrix uniform in the shader program.
void SetUniformMat4f (const std::string &name, const glm::mat4 &matrix)
Set a 4x4 matrix uniform in the shader program.
Private Member Functions
ShaderProgramSource ParseShader (const std::string &filepath)
Parse shader source code from a file.
unsigned int CompileShader (unsigned int type, const std::string &source)
Compile a shader from source code.
unsigned int CreateShader (const std::string &vertexShader, const std::string &fragmentShader)
Create a shader program from vertex and fragment shaders.
int GetUniformLocation (const std::string &name)
Get the location of a uniform variable in the shader program.
Private Attributes
std::string m_FilePath
Filepath to the shader source code.
unsigned int m_RendererID
OpenGL renderer ID for the shader program.
std::unordered_map< std::string, int > m_UniformLocationCache
Cache for uniform locations.
Detailed Description
A class responsible for loading, compiling, and managing shader programs.
Definition at line 26 of file Shader.h.
Constructor & Destructor Documentation
Shader()
Shader::Shader (const std::string & filepath)
Construct a shader object and load shader source code from a file.
Parameters
filepath The path to the shader source code file.
Definition at line 7 of file Shader.cpp.
                                        : m_FilePath(filepath), m_RendererID(0)
{
    ShaderProgramSource source = ParseShader(filepath);
    m_RendererID = CreateShader(source.VertexSource, source.FragmentSource);
}
References CreateShader(), m_RendererID, and ParseShader().
Referenced by main().
~Shader()
Shader::~Shader ()
Destructor to clean up shader resources.
Definition at line 13 of file Shader.cpp.
{
    glDeleteProgram(m_RendererID);
}
References m_RendererID.
Member Function Documentation
Bind()
void Shader::Bind () const
Bind the shader for rendering.
Definition at line 93 of file Shader.cpp.
{
    glUseProgram(m_RendererID);
}
References m_RendererID.
Referenced by Skybox::Render(), Terrain::render(), Renderer::Render(), and Renderer::TerrainRender().
CompileShader()
unsigned int Shader::CompileShader (unsigned int type, const std::string & source) private
Compile a shader from source code.
Parameters
type The type of shader (GL_VERTEX_SHADER or GL_FRAGMENT_SHADER).
source The shader source code.
Returns
The OpenGL ID of the compiled shader.
Definition at line 52 of file Shader.cpp.
{
    unsigned int id = glCreateShader(type);
    const char* src = source.c_str();
    glShaderSource(id, 1, &src, nullptr);
    glCompileShader(id);
    int result;
    glGetShaderiv(id, GL_COMPILE_STATUS, &result);
    if (result == GL_FALSE)
    {
        int length;
        glGetShaderiv(id, GL_INFO_LOG_LENGTH, &length);
        char* message = (char*)alloca(length * sizeof(char));
        glGetShaderInfoLog(id, length, &length, message);
        std::cout << "Failed to compile " << (type == GL_VERTEX_SHADER ? "vertex" : "fragment") << " shader!" << std::endl;
        std::cout << message << std::endl;
        glDeleteShader(id);
        return 0;
    }
    return id;
}
CreateShader()
unsigned int Shader::CreateShader (const std::string & vertexShader, const std::string & fragmentShader) private
Create a shader program from vertex and fragment shaders.
Parameters
vertexShader The source code for the vertex shader.
fragmentShader The source code for the fragment shader.
Returns
The OpenGL ID of the shader program.
Definition at line 76 of file Shader.cpp.
{
    unsigned int program = glCreateProgram();
    unsigned int vs = CompileShader(GL_VERTEX_SHADER, vertexShader);
    unsigned int fs = CompileShader(GL_FRAGMENT_SHADER, fragmentShader);
    glAttachShader(program, vs);
    glAttachShader(program, fs);
    glLinkProgram(program);
    glValidateProgram(program);
    glDeleteShader(vs);
    glDeleteShader(fs);
    return program;
}
Referenced by Shader().
GetUniformLocation()
int Shader::GetUniformLocation (const std::string & name) private
Get the location of a uniform variable in the shader program.
Parameters
name The name of the uniform variable.
Returns
The location of the uniform variable.
Definition at line 173 of file Shader.cpp.
{
    if (m_UniformLocationCache.find(name) != m_UniformLocationCache.end())
    {
        return m_UniformLocationCache[name];
    }
    int location = glGetUniformLocation(m_RendererID, name.c_str());
    if (location == -1)
    {
        std::cout << "Warning: uniform '" << name << "' doesn't exist!" << std::endl;
    }
    m_UniformLocationCache[name] = location;
    return location;
}
Referenced by SetUniform1f(), SetUniform1fv(), and SetUniform1i().
ParseShader()
ShaderProgramSource Shader::ParseShader (const std::string & filepath) private
Parse shader source code from a file.
Parameters
filepath The path to the shader source code file.
Returns
A ShaderProgramSource containing vertex and fragment shader source code.
Definition at line 18 of file Shader.cpp.
{
    std::ifstream stream(filepath);
    enum class ShaderType
    {
        NONE = -1, VERTEX = 0, FRAGMENT = 1
    };
    std::string line;
    std::stringstream ss[2];
    ShaderType type = ShaderType::NONE;
    while (getline(stream, line))
    {
        if (line.find("#shader") != std::string::npos)
        {
            if (line.find("vertex") != std::string::npos)
            {
                type = ShaderType::VERTEX;
            }
            else if (line.find("fragment") != std::string::npos)
            {
                type = ShaderType::FRAGMENT;
            }
        }
        else
        {
            ss[(int)type] << line << '\n';
        }
    }
    return { ss[0].str(), ss[1].str() };
}
Referenced by Shader().
SetUniform1f()
void Shader::SetUniform1f (const std::string & name, float value)
Set a floating-point uniform in the shader program.
Parameters
name The name of the uniform variable.
value The float value to set.
Definition at line 108 of file Shader.cpp.
{
    glUniform1f(GetUniformLocation(name), value);
}
References GetUniformLocation().
Referenced by Terrain::render().
SetUniform1fv()
void Shader::SetUniform1fv (const std::string & name, unsigned int size, float * values)
Definition at line 113 of file Shader.cpp.
{
    glUniform1fv(GetUniformLocation(name), size, values);
}
References GetUniformLocation().
SetUniform1i()
void Shader::SetUniform1i (const std::string & name, int value)
Set an integer uniform in the shader program.
Parameters
name The name of the uniform variable.
value The integer value to set.
Definition at line 103 of file Shader.cpp.
{
    glUniform1i(GetUniformLocation(name), value);
}
References GetUniformLocation().
Referenced by Terrain::render().
SetUniform2f()
void Shader::SetUniform2f (const std::string & name, const glm::vec2 & value)
Set a 2-component floating point uniform in the shader program.
Parameters
name The name of the uniform variable.
value A glm::vec2 containing the values to set.
Definition at line 118 of file Shader.cpp.
{
    glUniform2f(GetUniformLocation(name), value.x, value.y);
}
SetUniform3f()
void Shader::SetUniform3f (const std::string & name, const glm::vec3 & value)
Set a 3-component floating point uniform in the shader program.
Parameters
name The name of the uniform variable.
value A glm::vec3 containing the values to set.
Definition at line 123 of file Shader.cpp.
{
    glUniform3f(GetUniformLocation(name), value.x, value.y, value.z);
}
SetUniform3fv()
void Shader::SetUniform3fv (const std::string & name, unsigned int size, const std::vector< glm::vec3 > & value)
Definition at line 128 of file Shader.cpp.
{
    glm::vec3* values = new glm::vec3[size];
    for (int i = 0; i < size; i++)
    {
        if (i < value.size())
        {
            values[i] = value[i];
        }
    }
    glUniform3fv(GetUniformLocation(name), size, &values[0][0]);
}
SetUniform4f()
void Shader::SetUniform4f (const std::string & name, const glm::vec4 & value)
Set a 4-component floating point uniform in the shader program.
Parameters
name The name of the uniform variable.
value A glm::vec4 containing the values to set.
Definition at line 143 of file Shader.cpp.
{
    glUniform4f(GetUniformLocation(name), value.x, value.y, value.z, value.w);
}
SetUniform4fv()
void Shader::SetUniform4fv (const std::string & name, unsigned int size, const std::vector< glm::vec4 > & value)
Definition at line 148 of file Shader.cpp.
{
    glm::vec4* values = new glm::vec4[size];
    for (int i = 0; i < size; i++)
    {
        if (i < value.size())
        {
            values[i] = value[i];
        }
    }
    glUniform4fv(GetUniformLocation(name), size, &values[0][0]);
}
SetUniformMat3f()
void Shader::SetUniformMat3f (const std::string & name, const glm::mat3 & matrix)
Set a 3x3 matrix uniform in the shader program.
Parameters
name The name of the uniform variable.
matrix A glm::mat3 representing the matrix to set.
Definition at line 163 of file Shader.cpp.
{
    glUniformMatrix3fv(GetUniformLocation(name), 1, GL_FALSE, &matrix[0][0]);
}
SetUniformMat4f()
void Shader::SetUniformMat4f (const std::string & name, const glm::mat4 & matrix)
Set a 4x4 matrix uniform in the shader program.
Parameters
name The name of the uniform variable.
matrix A glm::mat4 representing the matrix to set.
Definition at line 168 of file Shader.cpp.
{
    glUniformMatrix4fv(GetUniformLocation(name), 1, GL_FALSE, &matrix[0][0]);
}
Unbind()
void Shader::Unbind () const
Unbind the shader.
Definition at line 98 of file Shader.cpp.
{
    glUseProgram(0);
}
Referenced by Terrain::render().
Member Data Documentation
m_FilePath
std::string Shader::m_FilePath private
Filepath to the shader source code.
Definition at line 28 of file Shader.h.
m_RendererID
unsigned int Shader::m_RendererID private
OpenGL renderer ID for the shader program.
Definition at line 29 of file Shader.h.
Referenced by Bind(), Shader(), and ~Shader().
m_UniformLocationCache
std::unordered_map<std::string, int> Shader::m_UniformLocationCache private
Cache for uniform locations.
Definition at line 30 of file Shader.h.
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/Shader.h
AAAAGameEngine2/AAAAGameEngine2/src/Shader.cpp