AAAAEngine: GraphicsUtility Class Reference
GraphicsUtility Class Reference
Utility class for graphics-related operations.
#include <GraphicsUtility.h>
Public Types
using Window = GLFWwindow*
using KeyCallback = std::function<void(GLFWwindow*, int, int, int, int)>
using CursorPosCallback = std::function<void(GLFWwindow*, double, double)>
Static Public Member Functions
static int Initialise ()
Initializes GLFW.
static int initialiseOpenGLExtensions ()
Initializes OpenGL extensions using GLEW.
static void Terminate ()
Terminates GLFW.
static void destroyWindow (Window window)
Destroys a window.
static GLFWwindow * CreateWindow (const char *title)
Creates a GLFW window.
static GLFWwindow * CreateWindow (const char *title, int width, int height)
Creates a GLFW window with specified dimensions.
static void makeContextCurrent (GLFWwindow *window)
Sets the current OpenGL context.
static void setFramebufferSizeCallback (GLFWwindow *window)
Sets the framebuffer size callback for a window.
static bool shouldClose (GLFWwindow *window)
Checks if a window should close.
static void swapBuffers (GLFWwindow *window)
Swaps the front and back buffers of a window.
static void pollEvents ()
Polls for events.
static void setWindowShouldClose (GLFWwindow *window, bool value)
Sets the should close flag for a window.
static void AddKeyCallback (KeyCallback callback)
Adds a key callback function.
static void AddCursorPosCallback (CursorPosCallback callback)
Adds a cursor position callback function.
static void SetClearColor (float red, float green, float blue, float alpha)
Sets the clear color for the color buffer.
static void Clear (int buffers)
Clears buffers to preset values.
static void Enable (GLenum cap)
Enables a specific OpenGL capability.
static void Disable (GLenum cap)
Disables a specific OpenGL capability.
static void Begin (GLenum mode)
Marks the beginning of vertex data definition.
static void End ()
Marks the end of vertex data definition.
static void Color3f (float red, float green, float blue)
Sets the current color.
static void TexCoord2f (float s, float t)
Sets the current texture coordinates.
static void Vertex3f (float x, float y, float z)
Sets the current vertex.
static void Normal3f (float nx, float ny, float nz)
Sets the current normal vector.
static void PolygonMode (GLenum face, GLenum mode)
Specifies the mode and face for polygon rasterization.
static void GenerateVertexArrays (GLsizei value, unsigned int *id)
Generates vertex array object names.
static void DeleteVertexArrays (GLsizei value, unsigned int *id)
Deletes named vertex array objects.
static void EnableVertexAttribArray (unsigned int index)
Enables a generic vertex attribute array.
static void VertexAttribPointer (unsigned int index, int size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer)
Defines an array of generic vertex attribute data.
static void BindVertexArray (unsigned int id)
Binds a vertex array object.
static void GenBuffers (GLsizei n, unsigned int *buffers)
Generates buffer object names.
static void BindBuffer (GLenum target, unsigned int buffer)
Binds a buffer to a buffer target.
static void BufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
Creates and initializes a buffer object's data store.
static void DeleteBuffers (GLsizei n, const unsigned int *buffers)
Deletes buffer objects.
static void GenTextures (GLsizei n, unsigned int *textures)
Generates texture names.
static void BindTexture (GLenum target, unsigned int texture)
Binds a named texture to a texture target.
static void TexParameteri (GLenum target, GLenum pname, int param)
Sets texture parameters.
static void TexImage2D (GLenum target, int level, int internalformat, GLsizei width, GLsizei height, int border, GLenum format, GLenum type, const void *pixels)
Specifies a two-dimensional texture image.
static void DeleteTextures (GLsizei n, const unsigned int *textures)
Deletes named textures.
static unsigned int CreateShader (GLenum type)
Creates a shader object.
static void ShaderSource (unsigned int shader, GLsizei count, const char *const *string, const int *length)
Sets the source code in a shader object.
static void CompileShader (unsigned int shader)
Compiles a shader object.
static void GetShaderiv (unsigned int shader, GLenum pname, int *params)
Returns a parameter from a shader object.
static void GetShaderInfoLog (unsigned int shader, GLsizei maxLength, GLsizei *length, char *infoLog)
Returns the info log for a shader object.
static void DeleteShader (unsigned int shader)
Deletes a shader object.
static unsigned int CreateProgram ()
Creates a program object.
static void DeleteProgram (unsigned int id)
Deletes a program object.
static void AttachShader (unsigned int program, unsigned int shader)
Attaches a shader object to a program object.
static void LinkProgram (unsigned int program)
Links a program object.
static void ValidateProgram (unsigned int program)
Validates a program object.
static void UseProgram (unsigned int program)
Sets the current program object.
static int GetUniformLocation (unsigned int program, const char *name)
Returns the location of a uniform variable.
static void Uniform1i (int location, int v0)
Sets the value of a uniform variable of type int.
static void Uniform1f (int location, GLfloat v0)
Sets the value of a uniform variable of type float.
static void Uniform2f (int location, GLfloat v0, GLfloat v1)
Sets the value of a uniform variable of type vec2.
static void Uniform3f (int location, GLfloat v0, GLfloat v1, GLfloat v2)
Sets the value of a uniform variable of type vec3.
static void Uniform4f (int location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
Sets the value of a uniform variable of type vec4.
static void Uniform1fv (int location, GLsizei count, const GLfloat *value)
Sets the value of a uniform array variable of type float.
static void Uniform3fv (int location, GLsizei count, const GLfloat *value)
Sets the value of a uniform array variable of type vec3.
static void Uniform4fv (int location, GLsizei count, const GLfloat *value)
Sets the value of a uniform array variable of type vec4.
static void UniformMatrix3fv (int location, GLsizei count, GLboolean transpose, const GLfloat *value)
Sets the value of a uniform matrix variable of type mat3.
static void UniformMatrix4fv (int location, GLsizei count, GLboolean transpose, const GLfloat *value)
Sets the value of a uniform matrix variable of type mat4.
static void DrawElements (GLenum mode, GLsizei count, GLenum type, const void *indices)
Renders primitives from array data.
static void GenerateMipMap (GLenum target)
Generates mipmaps for a specified texture target.
static float GetWindowHeight (Window window)
Gets the height of a window.
static float GetWindowWidth (Window window)
Gets the width of a window.
static void DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, void *indices, GLint basevertex)
Renders primitives from array data with a base vertex.
Static Private Member Functions
static void KeyCallbackDispatcher (GLFWwindow *window, int key, int scancode, int action, int mods)
static void CursorPosCallbackDispatcher (GLFWwindow *window, double xpos, double ypos)
static void errorCallback (int error, const char *description)
static void framebufferSizeCallback (GLFWwindow *window, int width, int height)
Callback function called when the framebuffer size of a window changes.
Static Private Attributes
static std::vector< KeyCallback > keyCallbacks
static std::vector< CursorPosCallback > cursorPosCallbacks
Detailed Description
Utility class for graphics-related operations.
Definition at line 182 of file GraphicsUtility.h.
Member Typedef Documentation
CursorPosCallback
using GraphicsUtility::CursorPosCallback = std::function<void(GLFWwindow*, double, double)>
Definition at line 189 of file GraphicsUtility.h.
KeyCallback
using GraphicsUtility::KeyCallback = std::function<void(GLFWwindow*, int, int, int, int)>
Definition at line 187 of file GraphicsUtility.h.
Window
using GraphicsUtility::Window = GLFWwindow*
Definition at line 185 of file GraphicsUtility.h.
Member Function Documentation
AddCursorPosCallback()
void GraphicsUtility::AddCursorPosCallback (CursorPosCallback callback) static
Adds a cursor position callback function.
Parameters
callback The callback function to add.
Definition at line 88 of file GraphicsUtility.cpp.
{
    cursorPosCallbacks.push_back(callback);
}
AddKeyCallback()
void GraphicsUtility::AddKeyCallback (KeyCallback callback) static
Adds a key callback function.
Parameters
callback The callback function to add.
Definition at line 84 of file GraphicsUtility.cpp.
{
    keyCallbacks.push_back(callback);
}
AttachShader()
void GraphicsUtility::AttachShader (unsigned int program, unsigned int shader) static
Attaches a shader object to a program object.
Parameters
program The name of the program object.
shader The name of the shader object to attach.
Definition at line 258 of file GraphicsUtility.cpp.
{
    glAttachShader(program, shader);
}
Begin()
void GraphicsUtility::Begin (GLenum mode) static
Marks the beginning of vertex data definition.
Parameters
mode The primitive type to begin drawing.
Definition at line 113 of file GraphicsUtility.cpp.
{
    glBegin(mode);
}
BindBuffer()
void GraphicsUtility::BindBuffer (GLenum target, unsigned int buffer) static
Binds a buffer to a buffer target.
Parameters
target The target to which the buffer will be bound.
buffer The name of the buffer object to bind.
Definition at line 178 of file GraphicsUtility.cpp.
{
    glBindBuffer(target, buffer);
}
BindTexture()
void GraphicsUtility::BindTexture (GLenum target, unsigned int texture) static
Binds a named texture to a texture target.
Parameters
target The texture target to which the texture will be bound.
texture The name of the texture to bind.
Definition at line 198 of file GraphicsUtility.cpp.
{
    glBindTexture(target, texture);
}
BindVertexArray()
void GraphicsUtility::BindVertexArray (unsigned int id) static
Binds a vertex array object.
Parameters
id The name of the vertex array object to bind.
Definition at line 168 of file GraphicsUtility.cpp.
{
    glBindVertexArray(id);
}
Referenced by VertexArray::Bind(), and VertexArray::Unbind().
BufferData()
void GraphicsUtility::BufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage) static
Creates and initializes a buffer object's data store.
Parameters
target The target buffer object.
size The size in bytes of the buffer object's new data store.
data Pointer to the data that will be copied into the data store.
usage The expected usage pattern of the data store.
Definition at line 183 of file GraphicsUtility.cpp.
{
    glBufferData(target, size, data, usage);
}
Clear()
void GraphicsUtility::Clear (int buffers) static
Clears buffers to preset values.
Parameters
buffers Bitwise OR of buffer bits indicating the buffers to be cleared.
Definition at line 98 of file GraphicsUtility.cpp.
{
    glClear(buffers);
}
Referenced by Renderer::Clear().
Color3f()
void GraphicsUtility::Color3f (float red, float green, float blue) static
Sets the current color.
Parameters
red Red component of the color.
green Green component of the color.
blue Blue component of the color.
Definition at line 123 of file GraphicsUtility.cpp.
{
    glColor3f(red, green, blue);
}
CompileShader()
void GraphicsUtility::CompileShader (unsigned int shader) static
Compiles a shader object.
Parameters
shader The name of the shader object.
Definition at line 228 of file GraphicsUtility.cpp.
{
    glCompileShader(shader);
}
CreateProgram()
unsigned int GraphicsUtility::CreateProgram () static
Creates a program object.
Returns
The name (ID) of the program object.
Definition at line 248 of file GraphicsUtility.cpp.
{
    return glCreateProgram();
}
CreateShader()
unsigned int GraphicsUtility::CreateShader (GLenum type) static
Creates a shader object.
Parameters
type The type of shader to create.
Returns
The name (ID) of the shader object.
Definition at line 218 of file GraphicsUtility.cpp.
{
    return glCreateShader(type);
}
CreateWindow() [1/2]
GLFWwindow * GraphicsUtility::CreateWindow (const char * title) static
Creates a GLFW window.
Parameters
title Title of the window.
Returns
Pointer to the created window.
Definition at line 34 of file GraphicsUtility.cpp.
{
    // Get the primary monitor (you can use other monitors if needed)
    GLFWmonitor* monitor = glfwGetPrimaryMonitor();
    // Get the video mode of the monitor
    const GLFWvidmode* mode = glfwGetVideoMode(monitor);
    GLFWwindow* window = glfwCreateWindow(mode->width, mode->height, "My GLFW Window", NULL, NULL);
    if (!window) {
        glfwTerminate();
        exit(EXIT_FAILURE);
    }
    return window;
}
CreateWindow() [2/2]
GLFWwindow * GraphicsUtility::CreateWindow (const char * title, int width, int height) static
Creates a GLFW window with specified dimensions.
Parameters
title Title of the window.
width Width of the window.
height Height of the window.
Returns
Pointer to the created window.
Definition at line 50 of file GraphicsUtility.cpp.
{
    GLFWwindow* window = glfwCreateWindow(width, height, "My GLFW Window", NULL, NULL);
    if (!window) {
        glfwTerminate();
        exit(EXIT_FAILURE);
    }
    return window;
}
CursorPosCallbackDispatcher()
static void GraphicsUtility::CursorPosCallbackDispatcher (GLFWwindow * window, double xpos, double ypos) static private
DeleteBuffers()
void GraphicsUtility::DeleteBuffers (GLsizei n, const unsigned int * buffers) static
Deletes buffer objects.
Parameters
n The number of buffer objects to delete.
buffers Pointer to an array containing the buffer objects to delete.
Definition at line 188 of file GraphicsUtility.cpp.
{
    glDeleteBuffers(n, buffers);
}
DeleteProgram()
void GraphicsUtility::DeleteProgram (unsigned int id) static
Deletes a program object.
Parameters
id The name of the program object.
Definition at line 253 of file GraphicsUtility.cpp.
{
    glDeleteProgram(id);
}
DeleteShader()
void GraphicsUtility::DeleteShader (unsigned int shader) static
Deletes a shader object.
Parameters
shader The name of the shader object.
Definition at line 243 of file GraphicsUtility.cpp.
{
    glDeleteShader(shader);
}
DeleteTextures()
void GraphicsUtility::DeleteTextures (GLsizei n, const unsigned int * textures) static
Deletes named textures.
Parameters
n The number of textures to delete.
textures Pointer to an array containing the texture names to delete.
Definition at line 213 of file GraphicsUtility.cpp.
{
    glDeleteTextures(n, textures);
}
DeleteVertexArrays()
void GraphicsUtility::DeleteVertexArrays (GLsizei value, unsigned int * id) static
Deletes named vertex array objects.
Parameters
value The number of vertex array object names to delete.
id Pointer to an array containing the vertex array object names to delete.
Definition at line 153 of file GraphicsUtility.cpp.
{
    glDeleteVertexArrays(value, id);
}
destroyWindow()
void GraphicsUtility::destroyWindow (Window window) static
Destroys a window.
Parameters
window The window to destroy.
Definition at line 29 of file GraphicsUtility.cpp.
{
    glfwDestroyWindow(window);
}
Disable()
void GraphicsUtility::Disable (GLenum cap) static
Disables a specific OpenGL capability.
Parameters
cap The capability to disable.
Definition at line 108 of file GraphicsUtility.cpp.
{
    glDisable(cap);
}
DrawElements()
void GraphicsUtility::DrawElements (GLenum mode, GLsizei count, GLenum type, const void * indices) static
Renders primitives from array data.
Parameters
mode The primitive type to render.
count The number of elements to be rendered.
type The type of the values in indices.
indices Pointer to the location where the indices are stored.
Definition at line 333 of file GraphicsUtility.cpp.
{
    glDrawElements(mode, count, type, indices);
}
DrawElementsBaseVertex()
void GraphicsUtility::DrawElementsBaseVertex (GLenum mode, GLsizei count, GLenum type, void * indices, GLint basevertex) static
Renders primitives from array data with a base vertex.
Parameters
mode The primitive type to render.
count The number of elements to be rendered.
type The type of the values in indices.
indices Pointer to the location where the indices are stored.
basevertex The value to add to each element of indices when choosing elements from the enabled vertex arrays.
Definition at line 363 of file GraphicsUtility.cpp.
{
    glDrawElementsBaseVertex(mode, count, type, indices, basevertex);
}
Enable()
void GraphicsUtility::Enable (GLenum cap) static
Enables a specific OpenGL capability.
Parameters
cap The capability to enable.
Definition at line 103 of file GraphicsUtility.cpp.
{
    glEnable(cap);
}
EnableVertexAttribArray()
void GraphicsUtility::EnableVertexAttribArray (unsigned int index) static
Enables a generic vertex attribute array.
Parameters
index The index of the generic vertex attribute array to enable.
Definition at line 158 of file GraphicsUtility.cpp.
{
    glEnableVertexAttribArray(index);
}
End()
void GraphicsUtility::End () static
Marks the end of vertex data definition.
Definition at line 118 of file GraphicsUtility.cpp.
{
    glEnd();
}
errorCallback()
static void GraphicsUtility::errorCallback (int error, const char * description) inline static private
Definition at line 687 of file GraphicsUtility.h.
{
        std::cerr << "GLFW Error " << error << ": " << description << std::endl;
    }
Referenced by Initialise().
framebufferSizeCallback()
void GraphicsUtility::framebufferSizeCallback (GLFWwindow * window, int width, int height) static private
Callback function called when the framebuffer size of a window changes.
Parameters
window The GLFW window whose framebuffer size changed.
width The new width of the framebuffer.
height The new height of the framebuffer.
Definition at line 382 of file GraphicsUtility.cpp.
{
    glViewport(0, 0, width, height); // Adjust the viewport
}
GenBuffers()
void GraphicsUtility::GenBuffers (GLsizei n, unsigned int * buffers) static
Generates buffer object names.
Parameters
n The number of buffer object names to generate.
buffers Pointer to an array in which the generated buffer object names are stored.
Definition at line 173 of file GraphicsUtility.cpp.
{
    glGenBuffers(n, buffers);
}
GenerateMipMap()
void GraphicsUtility::GenerateMipMap (GLenum target) static
Generates mipmaps for a specified texture target.
Parameters
target The target texture.
Definition at line 338 of file GraphicsUtility.cpp.
{
    glGenerateMipmap(target);
}
GenerateVertexArrays()
void GraphicsUtility::GenerateVertexArrays (GLsizei value, unsigned int * id) static
Generates vertex array object names.
Parameters
value The number of vertex array object names to generate.
id Pointer to an array in which the generated vertex array object names are stored.
Definition at line 148 of file GraphicsUtility.cpp.
{
    glGenVertexArrays(value, id);
}
GenTextures()
void GraphicsUtility::GenTextures (GLsizei n, unsigned int * textures) static
Generates texture names.
Parameters
n The number of texture names to generate.
textures Pointer to an array in which the generated texture names are stored.
Definition at line 193 of file GraphicsUtility.cpp.
{
    glGenTextures(n, textures);
}
GetShaderInfoLog()
void GraphicsUtility::GetShaderInfoLog (unsigned int shader, GLsizei maxLength, GLsizei * length, char * infoLog) static
Returns the info log for a shader object.
Parameters
shader The name of the shader object.
maxLength The maximum length of the info log.
length Pointer to an integer where the length of the info log will be stored.
infoLog Pointer to a character array where the info log will be stored.
Definition at line 238 of file GraphicsUtility.cpp.
{
    glGetShaderInfoLog(shader, maxLength, length, infoLog);
}
GetShaderiv()
void GraphicsUtility::GetShaderiv (unsigned int shader, GLenum pname, int * params) static
Returns a parameter from a shader object.
Parameters
shader The name of the shader object.
pname The parameter to query.
params Pointer to an integer where the parameter value will be stored.
Definition at line 233 of file GraphicsUtility.cpp.
{
    glGetShaderiv(shader, pname, params);
}
GetUniformLocation()
int GraphicsUtility::GetUniformLocation (unsigned int program, const char * name) static
Returns the location of a uniform variable.
Parameters
program The name of the program object.
name The name of the uniform variable.
Returns
The location of the uniform variable.
Definition at line 278 of file GraphicsUtility.cpp.
{
    return glGetUniformLocation(program, name);
}
GetWindowHeight()
float GraphicsUtility::GetWindowHeight (Window window) static
Gets the height of a window.
Parameters
window The GLFW window.
Returns
The height of the window.
Definition at line 343 of file GraphicsUtility.cpp.
{
    int width;
    int height;
    glfwGetWindowSize(window, &width, &height);
    return (float)height;
}
GetWindowWidth()
float GraphicsUtility::GetWindowWidth (Window window) static
Gets the width of a window.
Parameters
window The GLFW window.
Returns
The width of the window.
Definition at line 353 of file GraphicsUtility.cpp.
{
    int width;
    int height;
    glfwGetWindowSize(window, &width, &height);
    return (float)width;
}
Initialise()
int GraphicsUtility::Initialise () static
Initializes GLFW.
Returns
0 if successful, -1 otherwise.
Definition at line 3 of file GraphicsUtility.cpp.
{
    // Initialize GLFW
    if (!glfwInit()) {
        std::cerr << "Error: GLFW initialization failed" << std::endl;
        return -1;
    }
    glfwSetErrorCallback(errorCallback);
}
References errorCallback().
Referenced by main().
initialiseOpenGLExtensions()
int GraphicsUtility::initialiseOpenGLExtensions () static
Initializes OpenGL extensions using GLEW.
Returns
0 if successful, -1 otherwise.
Definition at line 14 of file GraphicsUtility.cpp.
{
    // Initialize GLEW
    glewExperimental = GL_TRUE; // Needed for core profile
    if (glewInit() != GLEW_OK) {
        std::cerr << "Error: GLEW initialization failed" << std::endl;
        Terminate();
        return -1;
    }
}
References Terminate().
Referenced by main().
KeyCallbackDispatcher()
static void GraphicsUtility::KeyCallbackDispatcher (GLFWwindow * window, int key, int scancode, int action, int mods) static private
LinkProgram()
void GraphicsUtility::LinkProgram (unsigned int program) static
Links a program object.
Parameters
program The name of the program object.
Definition at line 263 of file GraphicsUtility.cpp.
{
    glLinkProgram(program);
}
makeContextCurrent()
void GraphicsUtility::makeContextCurrent (GLFWwindow * window) static
Sets the current OpenGL context.
Parameters
window The window with the desired context.
Definition at line 60 of file GraphicsUtility.cpp.
{
    glfwMakeContextCurrent(window);
}
Normal3f()
void GraphicsUtility::Normal3f (float nx, float ny, float nz) static
Sets the current normal vector.
Parameters
nx X-component of the normal vector.
ny Y-component of the normal vector.
nz Z-component of the normal vector.
Definition at line 138 of file GraphicsUtility.cpp.
{
    glNormal3f(nx, ny, nz);
}
pollEvents()
void GraphicsUtility::pollEvents () static
Polls for events.
Definition at line 76 of file GraphicsUtility.cpp.
{
    glfwPollEvents();
}
PolygonMode()
void GraphicsUtility::PolygonMode (GLenum face, GLenum mode) static
Specifies the mode and face for polygon rasterization.
Parameters
face The face for which to set the mode.
mode The rasterization mode.
Definition at line 143 of file GraphicsUtility.cpp.
{
    glPolygonMode(face, mode);
}
SetClearColor()
void GraphicsUtility::SetClearColor (float red, float green, float blue, float alpha) static
Sets the clear color for the color buffer.
Parameters
red Red component of the color.
green Green component of the color.
blue Blue component of the color.
alpha Alpha component of the color.
Definition at line 93 of file GraphicsUtility.cpp.
{
    glClearColor(red, green, blue, alpha);
}
setFramebufferSizeCallback()
void GraphicsUtility::setFramebufferSizeCallback (GLFWwindow * window) static
Sets the framebuffer size callback for a window.
Parameters
window The window to set the callback for.
Definition at line 64 of file GraphicsUtility.cpp.
{
    glfwSetFramebufferSizeCallback(window, framebufferSizeCallback);
}
setWindowShouldClose()
void GraphicsUtility::setWindowShouldClose (GLFWwindow * window, bool value) static
Sets the should close flag for a window.
Parameters
window The window to set the flag for.
value The value to set.
Definition at line 80 of file GraphicsUtility.cpp.
{
    glfwSetWindowShouldClose(window, value ? GLFW_TRUE : GLFW_FALSE);
}
ShaderSource()
void GraphicsUtility::ShaderSource (unsigned int shader, GLsizei count, const char *const * string, const int * length) static
Sets the source code in a shader object.
Parameters
shader The name of the shader object.
count The number of strings in the strings parameter.
string Array of pointers to strings containing the source code to be loaded into the shader.
length An array containing the lengths of each string in the strings array.
Definition at line 223 of file GraphicsUtility.cpp.
{
    glShaderSource(shader, count, string, length);
}
shouldClose()
bool GraphicsUtility::shouldClose (GLFWwindow * window) static
Checks if a window should close.
Parameters
window The window to check.
Returns
True if the window should close, false otherwise.
Definition at line 68 of file GraphicsUtility.cpp.
{
    return glfwWindowShouldClose(window);
}
swapBuffers()
void GraphicsUtility::swapBuffers (GLFWwindow * window) static
Swaps the front and back buffers of a window.
Parameters
window The window whose buffers to swap.
Definition at line 72 of file GraphicsUtility.cpp.
{
    glfwSwapBuffers(window);
}
Terminate()
void GraphicsUtility::Terminate () static
Terminates GLFW.
Definition at line 24 of file GraphicsUtility.cpp.
{
    glfwTerminate();
}
Referenced by initialiseOpenGLExtensions(), and main().
TexCoord2f()
void GraphicsUtility::TexCoord2f (float s, float t) static
Sets the current texture coordinates.
Parameters
s The s-coordinate of the texture.
t The t-coordinate of the texture.
Definition at line 128 of file GraphicsUtility.cpp.
{
    glTexCoord2f(s, t);
}
TexImage2D()
void GraphicsUtility::TexImage2D (GLenum target, int level, int internalformat, GLsizei width, GLsizei height, int border, GLenum format, GLenum type, const void * pixels) static
Specifies a two-dimensional texture image.
Parameters
target The target texture.
level The level-of-detail number.
internalformat The number of color components in the texture.
width The width of the texture image.
height The height of the texture image.
border The width of the border. Must be 0.
format The format of the pixel data.
type The data type of the pixel data.
pixels Pointer to the image data in memory.
Definition at line 208 of file GraphicsUtility.cpp.
{
    glTexImage2D(target, level, internalformat, width, height, border, format, type, pixels);
}
TexParameteri()
void GraphicsUtility::TexParameteri (GLenum target, GLenum pname, int param) static
Sets texture parameters.
Parameters
target The target of the operation.
pname The parameter name.
param The value of the parameter.
Definition at line 203 of file GraphicsUtility.cpp.
{
    glTexParameteri(target, pname, param);
}
Uniform1f()
void GraphicsUtility::Uniform1f (int location, GLfloat v0) static
Sets the value of a uniform variable of type float.
Parameters
location The location of the uniform variable.
v0 The value to set.
Definition at line 288 of file GraphicsUtility.cpp.
{
    glUniform1f(location, v0);
}
Uniform1fv()
void GraphicsUtility::Uniform1fv (int location, GLsizei count, const GLfloat * value) static
Sets the value of a uniform array variable of type float.
Parameters
location The location of the uniform variable.
count The number of elements in the array.
value Pointer to the array containing the values to set.
Definition at line 308 of file GraphicsUtility.cpp.
{
    glUniform1fv(location, count, value);
}
Uniform1i()
void GraphicsUtility::Uniform1i (int location, int v0) static
Sets the value of a uniform variable of type int.
Parameters
location The location of the uniform variable.
v0 The value to set.
Definition at line 283 of file GraphicsUtility.cpp.
{
    glUniform1i(location, v0);
}
Uniform2f()
void GraphicsUtility::Uniform2f (int location, GLfloat v0, GLfloat v1) static
Sets the value of a uniform variable of type vec2.
Parameters
location The location of the uniform variable.
v0 The value to set for the first component.
v1 The value to set for the second component.
Definition at line 293 of file GraphicsUtility.cpp.
{
    glUniform2f(location, v0, v1);
}
Uniform3f()
void GraphicsUtility::Uniform3f (int location, GLfloat v0, GLfloat v1, GLfloat v2) static
Sets the value of a uniform variable of type vec3.
Parameters
location The location of the uniform variable.
v0 The value to set for the first component.
v1 The value to set for the second component.
v2 The value to set for the third component.
Definition at line 298 of file GraphicsUtility.cpp.
{
    glUniform3f(location, v0, v1, v2);
}
Uniform3fv()
void GraphicsUtility::Uniform3fv (int location, GLsizei count, const GLfloat * value) static
Sets the value of a uniform array variable of type vec3.
Parameters
location The location of the uniform variable.
count The number of elements in the array.
value Pointer to the array containing the values to set.
Definition at line 313 of file GraphicsUtility.cpp.
{
    glUniform3fv(location, count, value);
}
Uniform4f()
void GraphicsUtility::Uniform4f (int location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) static
Sets the value of a uniform variable of type vec4.
Parameters
location The location of the uniform variable.
v0 The value to set for the first component.
v1 The value to set for the second component.
v2 The value to set for the third component.
v3 The value to set for the fourth component.
Definition at line 303 of file GraphicsUtility.cpp.
{
    glUniform4f(location, v0, v1, v2, v3);
}
Uniform4fv()
void GraphicsUtility::Uniform4fv (int location, GLsizei count, const GLfloat * value) static
Sets the value of a uniform array variable of type vec4.
Parameters
location The location of the uniform variable.
count The number of elements in the array.
value Pointer to the array containing the values to set.
Definition at line 318 of file GraphicsUtility.cpp.
{
    glUniform4fv(location, count, value);
}
UniformMatrix3fv()
void GraphicsUtility::UniformMatrix3fv (int location, GLsizei count, GLboolean transpose, const GLfloat * value) static
Sets the value of a uniform matrix variable of type mat3.
Parameters
location The location of the uniform variable.
count The number of elements in the array.
transpose Whether to transpose the matrix.
value Pointer to the array containing the matrix values to set.
Definition at line 323 of file GraphicsUtility.cpp.
{
    glUniformMatrix3fv(location, count, transpose, value);
}
UniformMatrix4fv()
void GraphicsUtility::UniformMatrix4fv (int location, GLsizei count, GLboolean transpose, const GLfloat * value) static
Sets the value of a uniform matrix variable of type mat4.
Parameters
location The location of the uniform variable.
count The number of elements in the array.
transpose Whether to transpose the matrix.
value Pointer to the array containing the matrix values to set.
Definition at line 328 of file GraphicsUtility.cpp.
{
    glUniformMatrix4fv(location, count, transpose, value);
}
UseProgram()
void GraphicsUtility::UseProgram (unsigned int program) static
Sets the current program object.
Parameters
program The name of the program object to use.
Definition at line 273 of file GraphicsUtility.cpp.
{
    glUseProgram(program);
}
ValidateProgram()
void GraphicsUtility::ValidateProgram (unsigned int program) static
Validates a program object.
Parameters
program The name of the program object.
Definition at line 268 of file GraphicsUtility.cpp.
{
    glValidateProgram(program);
}
Vertex3f()
void GraphicsUtility::Vertex3f (float x, float y, float z) static
Sets the current vertex.
Parameters
x X-coordinate of the vertex.
y Y-coordinate of the vertex.
z Z-coordinate of the vertex.
Definition at line 133 of file GraphicsUtility.cpp.
{
    glVertex3f(x, y, z);
}
VertexAttribPointer()
void GraphicsUtility::VertexAttribPointer (unsigned int index, int size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer) static
Defines an array of generic vertex attribute data.
Parameters
index The index of the generic vertex attribute array to modify.
size The number of components per generic vertex attribute.
type The data type of each component in the array.
normalized Whether the data should be normalized.
stride The byte offset between consecutive generic vertex attributes.
pointer The offset of the first component of the first generic vertex attribute in the array in the data store.
Definition at line 163 of file GraphicsUtility.cpp.
{
    glVertexAttribPointer(index, size, type, normalized, stride, pointer);
}
Member Data Documentation
cursorPosCallbacks
std::vector< GraphicsUtility::CursorPosCallback > GraphicsUtility::cursorPosCallbacks inline static private
Definition at line 679 of file GraphicsUtility.h.
keyCallbacks
std::vector< GraphicsUtility::KeyCallback > GraphicsUtility::keyCallbacks inline static private
Definition at line 678 of file GraphicsUtility.h.
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/GraphicsUtility.h
AAAAGameEngine2/AAAAGameEngine2/src/GraphicsUtility.cpp