AAAAEngine: Renderer Class Reference
Renderer Class Reference
A class responsible for rendering operations using OpenGL.
#include <Renderer.h>
Public Member Functions
void Clear () const
Clear the screen with the current clear color.
void Render (const VertexArray &va, const IndexBuffer &ib, const Shader &shader, GLenum drawMode) const
Draw the specified Entity using the provided shader.
void TerrainRender (const VertexArray &va, const IndexBuffer &ib, const Shader &shader, GLenum drawMode, GLsizei count, GLenum type, void *indices, GLint BaseVertex) const
Draw the specified terrain (CLOD style) using the provided shader.
Detailed Description
A class responsible for rendering operations using OpenGL.
Definition at line 13 of file Renderer.h.
Member Function Documentation
Clear()
void Renderer::Clear () const
Clear the screen with the current clear color.
Definition at line 4 of file Renderer.cpp.
{
    // Clear the screen
    GraphicsUtility::Clear(GraphicsEnum::COLOR_BUFFER_BIT | GraphicsEnum::DEPTH_BUFFER_BIT);
}
References GraphicsUtility::Clear(), COLOR_BUFFER_BIT, and DEPTH_BUFFER_BIT.
Render()
void Renderer::Render (const VertexArray & va, const IndexBuffer & ib, const Shader & shader, GLenum drawMode) const
Draw the specified Entity using the provided shader.
Parameters
va Vertex Array
ib Index Buffer
shader The Shader program to use for rendering.
drawMode The mode of drawing
Definition at line 10 of file Renderer.cpp.
{
    // Bind shader program
    shader.Bind();
    // Bind VAO and EBO
    va.Bind();
    ib.Bind();
    // Get the number of indices to draw from the IndexBuffer
    unsigned int count = ib.GetCount();
    // Draw using the specified draw mode
    GraphicsUtility::DrawElements(drawMode, count, GraphicsEnum::UNSIGNED_INT, nullptr);
}
References IndexBuffer::Bind(), Shader::Bind(), VertexArray::Bind(), and IndexBuffer::GetCount().
TerrainRender()
void Renderer::TerrainRender (const VertexArray & va, const IndexBuffer & ib, const Shader & shader, GLenum drawMode, GLsizei count, GLenum type, void * indices, GLint BaseVertex) const
Draw the specified terrain (CLOD style) using the provided shader.
Parameters
va Vertex Array
ib Index Buffer
shader The Shader program to use for rendering.
drawMode The mode of drawing
patchSize the size of the LOD patches
length the length of the heightmap
width of the heightmap
Definition at line 26 of file Renderer.cpp.
{
    shader.Bind();
    va.Bind();
    ib.Bind();
    GraphicsUtility::DrawElementsBaseVertex(drawMode, count, type, indices, BaseVertex);
}
References IndexBuffer::Bind(), Shader::Bind(), and VertexArray::Bind().
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/Renderer.h
AAAAGameEngine2/AAAAGameEngine2/src/Renderer.cpp