AAAAEngine: VertexBufferLayout Class Reference
VertexBufferLayout Class Reference
A class representing the layout of vertex data in a vertex buffer.
#include <VertexBufferLayout.h>
Public Member Functions
VertexBufferLayout ()
Constructor for the VertexBufferLayout class.
template<typename T >
void Push (unsigned int count)
Push a new element into the layout.
template<>
void Push (unsigned int count)
Push a float element into the layout.
template<>
void Push (unsigned int count)
Push a double element into the layout.
template<>
void Push (unsigned int count)
Push an unsigned int element into the layout.
template<>
void Push (unsigned int count)
Push an unsigned char element into the layout.
const std::vector< VertexBufferElement > GetElements () const
Get the elements in the layout.
unsigned int GetStride () const
Get the stride (size) of the layout.
Private Attributes
std::vector< VertexBufferElement > m_Elements
unsigned int m_Stride
Detailed Description
A class representing the layout of vertex data in a vertex buffer.
Definition at line 42 of file VertexBufferLayout.h.
Constructor & Destructor Documentation
VertexBufferLayout()
VertexBufferLayout::VertexBufferLayout () inline
Constructor for the VertexBufferLayout class.
Definition at line 51 of file VertexBufferLayout.h.
: m_Stride(0) {}
References m_Stride.
Member Function Documentation
GetElements()
const std::vector< VertexBufferElement > VertexBufferLayout::GetElements () const inline
Get the elements in the layout.
Returns
A vector of VertexBufferElement.
Definition at line 118 of file VertexBufferLayout.h.
{ return m_Elements; }
GetStride()
unsigned int VertexBufferLayout::GetStride () const inline
Get the stride (size) of the layout.
Returns
The stride (size) of the layout.
Definition at line 125 of file VertexBufferLayout.h.
{ return m_Stride; }
References m_Stride.
Push() [1/5]
template<typename T > void VertexBufferLayout::Push (unsigned int count) inline
Push a new element into the layout.
Template Parameters
T The data type of the element.
Parameters
count The number of elements.
Definition at line 60 of file VertexBufferLayout.h.
    {
        // You can add error handling here if needed
    }
Push() [2/5]
template<> void VertexBufferLayout::Push (unsigned int count) inline
Push a float element into the layout.
Parameters
count The number of float elements.
Definition at line 71 of file VertexBufferLayout.h.
    {
        m_Elements.push_back({ GraphicsEnum::FLOAT, count, GraphicsEnum::FALSE });
        m_Stride += count * VertexBufferElement::GetSizeOfType(GraphicsEnum::FLOAT);
    }
References FLOAT, VertexBufferElement::GetSizeOfType(), and m_Stride.
Push() [3/5]
template<> void VertexBufferLayout::Push (unsigned int count) inline
Push a double element into the layout.
Parameters
count The number of double elements.
Definition at line 83 of file VertexBufferLayout.h.
    {
        m_Elements.push_back({ GraphicsEnum::DOUBLE, count, GraphicsEnum::FALSE });
        m_Stride += count * VertexBufferElement::GetSizeOfType(GraphicsEnum::DOUBLE);
    }
References DOUBLE, VertexBufferElement::GetSizeOfType(), and m_Stride.
Push() [4/5]
template<> void VertexBufferLayout::Push (unsigned int count) inline
Push an unsigned int element into the layout.
Parameters
count The number of unsigned int elements.
Definition at line 95 of file VertexBufferLayout.h.
    {
        m_Elements.push_back({ GraphicsEnum::UNSIGNED_INT, count, GraphicsEnum::FALSE });
        m_Stride += count * VertexBufferElement::GetSizeOfType(GraphicsEnum::UNSIGNED_INT);
    }
References VertexBufferElement::GetSizeOfType(), m_Stride, and UNSIGNED_INT.
Push() [5/5]
template<> void VertexBufferLayout::Push (unsigned int count) inline
Push an unsigned char element into the layout.
Parameters
count The number of unsigned char elements.
Definition at line 107 of file VertexBufferLayout.h.
    {
        m_Elements.push_back({ GraphicsEnum::UNSIGNED_BYTE, count, GraphicsEnum::TRUE });
        m_Stride += count * VertexBufferElement::GetSizeOfType(GraphicsEnum::UNSIGNED_BYTE);
    }
References VertexBufferElement::GetSizeOfType(), m_Stride, and UNSIGNED_BYTE.
Member Data Documentation
m_Elements
std::vector<VertexBufferElement> VertexBufferLayout::m_Elements private
The elements in the layout.
Definition at line 44 of file VertexBufferLayout.h.
m_Stride
unsigned int VertexBufferLayout::m_Stride private
The stride (size) of the layout.
Definition at line 45 of file VertexBufferLayout.h.
Referenced by GetStride(), Push(), and VertexBufferLayout().
The documentation for this class was generated from the following file:
AAAAGameEngine2/AAAAGameEngine2/src/VertexBufferLayout.h