AAAAEngine: Skybox Class Reference
Skybox Class Reference
Class representing a skybox.
#include <Skybox.h>
Public Member Functions
Skybox (std::vector< std::string > &paths)
Constructs a Skybox object with the given paths to skybox textures.
~Skybox ()=default
Default destructor for Skybox.
void Render (const Renderer &renderer, Shader &shader, const glm::mat4 &viewMatrix, const glm::mat4 &projectionMatrix)
Renders the skybox.
Private Attributes
std::vector< std::string > & paths
unsigned int textureID
std::shared_ptr< VertexArray > m_VAO
std::shared_ptr< VertexBuffer > m_VBO
std::shared_ptr< IndexBuffer > m_IBO
Detailed Description
Class representing a skybox.
Definition at line 18 of file Skybox.h.
Constructor & Destructor Documentation
Skybox()
Skybox::Skybox (std::vector< std::string > & paths)
Constructs a Skybox object with the given paths to skybox textures.
Parameters
paths Vector containing paths to skybox textures.
Definition at line 3 of file Skybox.cpp.
                                         : paths(paths)
{
    textureID = TextureManager::GetInstance().LoadTexture(paths, TextureType::CUBEMAP);
    // Define the vertices for the skybox (a cube)
    float skyboxVertices[] = {
        //   Coordinates
        -1.0f, -1.0f,  1.0f,//        7--------6
         1.0f, -1.0f,  1.0f,//       /|       /|
         1.0f, -1.0f, -1.0f,//      4--------5 |
        -1.0f, -1.0f, -1.0f,//      | |      | |
        -1.0f,  1.0f,  1.0f,//      | 3------|-2
         1.0f,  1.0f,  1.0f,//      |/       |/
         1.0f,  1.0f, -1.0f,//      0--------1
        -1.0f,  1.0f, -1.0f
    };
    unsigned int skyboxIndices[] =
    {
        // Right
        1, 2, 6,
        6, 5, 1,
        // Left
        0, 4, 7,
        7, 3, 0,
        // Top
        4, 5, 6,
        6, 7, 4,
        // Bottom
        0, 3, 2,
        2, 1, 0,
        // Back
        0, 1, 5,
        5, 4, 0,
        // Front
        3, 7, 6,
        6, 2, 3
    };
    // Bind and fill the VBO with the skybox vertices
    m_VBO = std::make_shared<VertexBuffer>(skyboxVertices, sizeof(skyboxVertices));
    // Setup vertex layout
    VertexBufferLayout layout;
    layout.Push<float>(3); // positions
    // Add vertex layout to VAO
    m_VAO = std::make_shared<VertexArray>();
    m_VAO->AddBuffer(*m_VBO, layout);
    // Bind and fill the IBO with the skybox indices
    m_IBO = std::make_shared<IndexBuffer>(skyboxIndices, sizeof(skyboxIndices) / sizeof(skyboxIndices[0]));
}
~Skybox()
Skybox::~Skybox () default
Default destructor for Skybox.
Member Function Documentation
Render()
void Skybox::Render (const Renderer & renderer, Shader & shader, const glm::mat4 & viewMatrix, const glm::mat4 & projectionMatrix)
Renders the skybox.
Parameters
renderer Reference to the renderer.
shader Reference to the shader.
viewMatrix The view matrix.
projectionMatrix The projection matrix.
Definition at line 57 of file Skybox.cpp.
{
    glDepthFunc(GL_LEQUAL);
    // Bind the skybox texture
    TextureManager::GetInstance().Bind(textureID, TextureType::CUBEMAP);
    shader.Bind();
    glm::mat4 view = glm::mat4(glm::mat3(viewMatrix));
    glm::mat4 projection = projectionMatrix;
    shader.SetUniformMat4f("view", view);
    shader.SetUniformMat4f("projection", projection);
    renderer.Render(*m_VAO, *m_IBO, shader, GraphicsEnum::TRIANGLES);
    TextureManager::GetInstance().Unbind();
    glDepthFunc(GL_LESS);
}
References Shader::Bind(), TextureManager::Bind(), CUBEMAP, TextureManager::GetInstance(), textureID, and TextureManager::Unbind().
Member Data Documentation
m_IBO
std::shared_ptr<IndexBuffer> Skybox::m_IBO private
Index Buffer Object (IBO) to store the skybox indices.
Definition at line 25 of file Skybox.h.
m_VAO
std::shared_ptr<VertexArray> Skybox::m_VAO private
Vertex Array Object (VAO) to store the skybox vertices.
Definition at line 23 of file Skybox.h.
m_VBO
std::shared_ptr<VertexBuffer> Skybox::m_VBO private
Vertex Buffer Object (VBO) to store the skybox vertices.
Definition at line 24 of file Skybox.h.
paths
std::vector<std::string>& Skybox::paths private
Vector containing paths to skybox textures.
Definition at line 20 of file Skybox.h.
textureID
unsigned int Skybox::textureID private
ID of the skybox texture.
Definition at line 21 of file Skybox.h.
Referenced by Render().
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/Skybox.h
AAAAGameEngine2/AAAAGameEngine2/src/Skybox.cpp