AAAAEngine: IndexBuffer Class Reference
IndexBuffer Class Reference
A class for managing OpenGL index buffers.
#include <IndexBuffer.h>
Public Member Functions
IndexBuffer (const unsigned int *data, unsigned int count)
Constructor for IndexBuffer.
~IndexBuffer ()
Destructor for IndexBuffer.
void Bind () const
Bind the index buffer for rendering.
void Unbind () const
Unbind the currently bound index buffer.
unsigned int GetCount () const
Get the number of indices in the index buffer.
Private Attributes
unsigned int m_RenderedID
unsigned int m_Count
Detailed Description
A class for managing OpenGL index buffers.
The IndexBuffer class provides methods for creating, binding, and unbinding OpenGL index buffers used for indexed rendering of vertex data.
Definition at line 13 of file IndexBuffer.h.
Constructor & Destructor Documentation
IndexBuffer()
IndexBuffer::IndexBuffer (const unsigned int * data, unsigned int count)
Constructor for IndexBuffer.
Creates an OpenGL index buffer and initializes it with the provided data.
Parameters
data A pointer to the index data.
count The number of indices in the buffer.
Definition at line 5 of file IndexBuffer.cpp.
                                                                     : m_RenderedID(0), m_Count(count)
{
    GraphicsUtility::GenBuffers(1, &m_RenderedID);
    GraphicsUtility::BindBuffer(GraphicsEnum::ELEMENT_ARRAY_BUFFER, m_RenderedID);
    GraphicsUtility::BufferData(GraphicsEnum::ELEMENT_ARRAY_BUFFER, count * sizeof(unsigned int), data, GraphicsEnum::STATIC_DRAW);
}
References m_Count, and m_RenderedID.
~IndexBuffer()
IndexBuffer::~IndexBuffer ()
Destructor for IndexBuffer.
Cleans up and deallocates the OpenGL index buffer.
Definition at line 13 of file IndexBuffer.cpp.
{
    // Delete the OpenGL index buffer
    GraphicsUtility::DeleteBuffers(1, &m_RenderedID);
}
Member Function Documentation
Bind()
void IndexBuffer::Bind () const
Bind the index buffer for rendering.
Binds the index buffer for use in rendering operations.
Definition at line 21 of file IndexBuffer.cpp.
{
    GraphicsUtility::BindBuffer(GraphicsEnum::ELEMENT_ARRAY_BUFFER, m_RenderedID);
}
Referenced by Renderer::Render(), and Renderer::TerrainRender().
GetCount()
unsigned int IndexBuffer::GetCount () const inline
Get the number of indices in the index buffer.
Returns
The number of indices in the index buffer.
Definition at line 58 of file IndexBuffer.h.
{ return m_Count; }
References m_Count.
Referenced by Renderer::Render().
Unbind()
void IndexBuffer::Unbind () const
Unbind the currently bound index buffer.
Unbinds the currently bound index buffer, releasing it from rendering operations.
Definition at line 27 of file IndexBuffer.cpp.
{
    GraphicsUtility::BindBuffer(GraphicsEnum::ELEMENT_ARRAY_BUFFER, 0);
}
Member Data Documentation
m_Count
unsigned int IndexBuffer::m_Count private
The number of indices in the index buffer.
Definition at line 17 of file IndexBuffer.h.
Referenced by GetCount(), and IndexBuffer().
m_RenderedID
unsigned int IndexBuffer::m_RenderedID private
The OpenGL ID of the index buffer.
Definition at line 16 of file IndexBuffer.h.
Referenced by IndexBuffer().
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/IndexBuffer.h
AAAAGameEngine2/AAAAGameEngine2/src/IndexBuffer.cpp