AAAAEngine: Vector4 Class Reference
Vector4 Class Reference
Class representing a 4D vector.
#include <DataStructures.h>
Public Member Functions
Vector4 ()
Vector4 (float x, float y, float z, float w)
Vector4 (Vector3 vec, float w)
Vector4 (glm::vec4 vec)
float & x ()
float & y ()
float & z ()
float & w ()
int length ()
void normalise ()
operator glm::vec4 () const
const Vector4 & operator+ (const Vector4 &otherMat) const
Private Attributes
glm::vec4 data
Detailed Description
Class representing a 4D vector.
Definition at line 71 of file DataStructures.h.
Constructor & Destructor Documentation
Vector4() [1/4]
Vector4::Vector4 () inline
Definition at line 77 of file DataStructures.h.
: data(glm::vec4(0.0f)) {}
Vector4() [2/4]
Vector4::Vector4 (float x, float y, float z, float w) inline
Definition at line 78 of file DataStructures.h.
: data(glm::vec4(x, y, z, w)) {}
Referenced by operator*().
Vector4() [3/4]
Vector4::Vector4 (Vector3 vec, float w) inline
Definition at line 79 of file DataStructures.h.
: data(glm::vec4(vec.x(), vec.y(), vec.z(), w)) {}
Vector4() [4/4]
Vector4::Vector4 (glm::vec4 vec) inline
Definition at line 80 of file DataStructures.h.
: data(vec.x, vec.y, vec.z, vec.w) {}
Member Function Documentation
length()
int Vector4::length ()
Calculates the length of the vector.
Definition at line 104 of file DataStructures.cpp.
{
    return data.length();
}
normalise()
void Vector4::normalise ()
Normalizes the vector.
Definition at line 109 of file DataStructures.cpp.
{
    data = glm::normalize(data);
}
operator glm::vec4()
Vector4::operator glm::vec4 () const
Conversion operator to glm::vec4.
Definition at line 114 of file DataStructures.cpp.
{
    return data;
}
operator+()
const Vector4 & Vector4::operator+ (const Vector4 & otherMat) const
Addition operator for vectors.
Definition at line 119 of file DataStructures.cpp.
{
    return Vector4(this->data.x + other.data.x, this->data.y + other.data.y, this->data.z + other.data.z, this->data.w + other.data.w);
}
w()
float & Vector4::w ()
Returns a reference to the w component of the vector.
Definition at line 99 of file DataStructures.cpp.
{
    return data.w;
}
Referenced by operator*().
x()
float & Vector4::x ()
Returns a reference to the x component of the vector.
Definition at line 84 of file DataStructures.cpp.
{
    return data.x;
}
Referenced by operator*().
y()
float & Vector4::y ()
Returns a reference to the y component of the vector.
Definition at line 89 of file DataStructures.cpp.
{
    return data.y;
}
Referenced by operator*().
z()
float & Vector4::z ()
Returns a reference to the z component of the vector.
Definition at line 94 of file DataStructures.cpp.
{
    return data.z;
}
Referenced by operator*().
Member Data Documentation
data
glm::vec4 Vector4::data private
Internal data storage for the vector.
Definition at line 74 of file DataStructures.h.
The documentation for this class was generated from the following files:
AAAAGameEngine2/AAAAGameEngine2/src/DataStructures.h
AAAAGameEngine2/AAAAGameEngine2/src/DataStructures.cpp